steps:
  # 0. 显式拉取 Git 子模块
  - name: "gcr.io/cloud-builders/git"
    id: "Fetch Submodules"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git submodule init
        git submodule update

  # 1. 构建镜像
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        "--build-arg",
        "VITE_API_URL=https://genshinquiz-backend-594226160049.asia-northeast1.run.app", # 替换为你实际的后端 Cloud Run 地址
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/genshinquiz-frontend:$COMMIT_SHA",
        ".",
      ]

  # 2. 推送镜像到 Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/genshinquiz-frontend:$COMMIT_SHA",
      ]

  # 3. 部署到 Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "genshinquiz-frontend"
      - "--image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/genshinquiz-frontend:$COMMIT_SHA"
      - "--region=asia-northeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"

options:
  logging: CLOUD_LOGGING_ONLY
