/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { UserPrivate } from './userPrivate.ts';

export interface AuthResponse {
  /** JWT token */
  token: string;
  user: UserPrivate;
}
