/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type CreateQuizRequestCategory =
  (typeof CreateQuizRequestCategory)[keyof typeof CreateQuizRequestCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuizRequestCategory = {
  characters: 'characters',
  weapons: 'weapons',
  artifacts: 'artifacts',
  lore: 'lore',
  gameplay: 'gameplay',
} as const;
