/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionOptionBase } from './questionOptionBase.ts';

export type CreateQuestionOptionRequest = QuestionOptionBase & {
  /** 是否为正确答案 */
  is_answer: boolean;
};
