/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { CreateQuestionRequestQuestionType } from './createQuestionRequestQuestionType';

export interface CreateQuestionRequest {
  /**
   * @minLength 1
   * @maxLength 500
   */
  question_text: string;
  question_type: CreateQuestionRequestQuestionType;
  options?: string[];
  /** @minLength 1 */
  correct_answer: string;
  /** @maxLength 1000 */
  explanation?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  points: number;
  /** @minimum 1 */
  order_index: number;
}
