/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { CreateQuestionRequest } from './createQuestionRequest';
import type { CreateQuizRequestCategory } from './createQuizRequestCategory';
import type { CreateQuizRequestDifficulty } from './createQuizRequestDifficulty';

export interface CreateQuizRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /** @maxLength 1000 */
  description?: string;
  category: CreateQuizRequestCategory;
  difficulty: CreateQuizRequestDifficulty;
  /** @minItems 1 */
  questions: CreateQuestionRequest[];
  /**
   * @minimum 30
   * @maximum 3600
   */
  time_limit?: number;
  created_by: number;
}
