/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { PollBase } from './pollBase.ts';
import type { PollOptionBase } from './pollOptionBase.ts';

export type CreatePollRequest = PollBase & {
  /** 投票密码 */
  password?: string;
  options: PollOptionBase[];
};
