/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { CreateQuestionOptionRequest } from './createQuestionOptionRequest.ts';
import type { QuestionBase } from './questionBase.ts';

export type CreateQuestionRequest = QuestionBase & {
  options: CreateQuestionOptionRequest[];
};
