/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export interface CreateUserRequest {
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  email: string;
  /** @maxLength 100 */
  display_name?: string;
  avatar_url?: string;
}
