/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { ExamBase } from './examBase.ts';
import type { ExamQuestion } from './examQuestion.ts';

export type CreateExamRequest = ExamBase & {
  questions: ExamQuestion[];
};
