/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { Category } from './category';
import type { Difficulty } from './difficulty';
import type { LocalizedText } from './localizedText';

export interface ExamBase {
  public: boolean;
  title: LocalizedText;
  description?: LocalizedText;
  categories: Category[];
  difficulty: Difficulty;
  /** Time limit in seconds */
  time_limit: number;
}
