/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from './category.ts';
import type { Difficulty } from './difficulty.ts';
import type { LocalizedText } from './localizedText.ts';

export interface ExamBase {
  public: boolean;
  title: LocalizedText;
  description?: LocalizedText;
  categories: Category[];
  difficulty: Difficulty;
  /** Time limit in seconds */
  time_limit: number;
}
