/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { ExamLikeStatus } from './examLikeStatus';
import type { ExamQuestionsItem } from './examQuestionsItem';
import type { QuestionCategory } from './questionCategory';
import type { QuestionDifficulty } from './questionDifficulty';

export interface Exam {
  id: string;
  public: boolean;
  title: string;
  description?: string;
  categories?: QuestionCategory[];
  difficulty: QuestionDifficulty;
  questions: ExamQuestionsItem[];
  /** Time limit in seconds */
  time_limit?: number;
  created_by: string;
  created_at: Date;
  updated_at: Date;
  /** 点赞数 */
  likes?: number;
  /** 点赞状态：-1踩, 0未操作, 1赞 */
  likeStatus?: ExamLikeStatus;
}
