/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { ExamBase } from './examBase.ts';
import type { ExamQuestion } from './examQuestion.ts';
import type { LikeStatus } from './likeStatus.ts';

export type Exam = ExamBase & {
  id: string;
  created_by: string;
  created_at: Date;
  updated_at: Date;
  /** 点赞数 */
  likes_count: number;
  like_status: LikeStatus;
  questions: ExamQuestion[];
};
