/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type ExamQuestionsItem = {
  /** 题目ID */
  question_id: string;
  /** 在本测验中的顺序 */
  order_index?: number;
  /** 本题分值 */
  points?: number;
};
