/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type Gender = (typeof Gender)[keyof typeof Gender];

export const Gender = {
  unknown: 'unknown',
  male: 'male',
  female: 'female',
  other: 'other',
} as const;
