/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Exam } from './exam';

export type GetExams200 = {
  exams?: Exam[];
  total?: number;
};
