/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Exam } from './exam.ts';

export type GetExams200 = {
  exams: Exam[];
  total: number;
};
