/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type GetPollsType = (typeof GetPollsType)[keyof typeof GetPollsType];

export const GetPollsType = {
  all: 'all',
  available: 'available',
  expired: 'expired',
} as const;
