/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { GetPollsType } from './getPollsType';

export type GetPollsParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  type?: GetPollsType;
  query?: string;
  language?: string[];
  /**
   * 只返回指定用户创建的投票
   */
  created_by?: string;
  sortBy?: string;
  sortDesc?: boolean;
};
