/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Poll } from './poll.ts';

export type GetPolls200 = {
  polls: Poll[];
  total: number;
};
