/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Poll } from './poll';

export type GetPolls200 = {
  polls: Poll[];
  total: number;
};
