/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type GetQuizzesDifficulty = (typeof GetQuizzesDifficulty)[keyof typeof GetQuizzesDifficulty];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetQuizzesDifficulty = {
  easy: 'easy',
  medium: 'medium',
  hard: 'hard',
} as const;
