/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionCategory } from './questionCategory';
import type { QuestionDifficulty } from './questionDifficulty';

export type GetQuestionsParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  category?: QuestionCategory;
  difficulty?: QuestionDifficulty[];
  query?: string;
  language?: string[];
  sortBy?: string;
  sortDesc?: boolean;
};
