/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Quiz } from './quiz';

export type GetQuizzes200 = {
  quizzes?: Quiz[];
  total?: number;
  limit?: number;
  offset?: number;
};
