/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from './category.ts';
import type { Difficulty } from './difficulty.ts';

export type GetQuestionsParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  category?: Category;
  difficulty?: Difficulty[];
  query?: string;
  language?: string[];
  /**
   * 只返回指定用户创建的题目
   */
  created_by?: string;
  sortBy?: string;
  sortDesc?: boolean;
};
