/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export type GetUsers200 = {
  users?: User[];
  total?: number;
  limit?: number;
  offset?: number;
};
