/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { UserPublic } from './userPublic.ts';

export type GetUsers200 = {
  users: UserPublic[];
  total: number;
};
