/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersSortBy = (typeof GetUsersSortBy)[keyof typeof GetUsersSortBy];

export const GetUsersSortBy = {
  accuracy: 'accuracy',
  votes: 'votes',
  questions_created: 'questions_created',
  likes_received: 'likes_received',
} as const;
