/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Question } from './question.ts';

export type GetUserQuestions200 = {
  questions: Question[];
  total: number;
};
