/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Vote } from './vote';

export type GetVotes200 = {
  votes?: Vote[];
  total?: number;
};
