/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type GetVotesType = (typeof GetVotesType)[keyof typeof GetVotesType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetVotesType = {
  all: 'all',
  available: 'available',
  expired: 'expired',
} as const;
