/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Exam } from './exam.ts';
import type { Poll } from './poll.ts';
import type { Question } from './question.ts';

export interface HomePageData {
  popularExams: Exam[];
  latestQuestions: Question[];
  latestPolls: Poll[];
  popularPolls: Poll[];
}
