/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Exam } from './exam';
import type { Poll } from './poll';
import type { Question } from './question';

export interface HomePageData {
  popularExams: Exam[];
  latestQuestions: Question[];
  latestPolls: Poll[];
  popularPolls: Poll[];
}
