/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * Localized text keyed by language code.
Example: {"en-US": "Hello", "ja-JP": "こんにちは", "zh-CN": "你好"}

 */
export interface LocalizedText {
  [key: string]: string;
}
