/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export interface MySubmission {
  /** 答案是否正确 */
  is_correct: boolean;
  selected_option_ids: string[];
  /** 答题用时（秒） */
  time_spent: number;
  /** 提交时间 */
  submitted_at: Date;
}
