/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type OptionType = (typeof OptionType)[keyof typeof OptionType];

export const OptionType = {
  text: 'text',
  image: 'image',
  music: 'music',
} as const;
