/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type OptionType = (typeof OptionType)[keyof typeof OptionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OptionType = {
  text: 'text',
  image: 'image',
  music: 'music',
} as const;
