/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { LocalizedText } from './localizedText';
import type { OptionType } from './optionType';

export interface PollOptionBase {
  option_type: OptionType;
  /** 选项文本 */
  text: LocalizedText;
  /** 选项描述 */
  description?: LocalizedText;
  media_url?: string;
}
