/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { PollOptionBase } from './pollOptionBase.ts';

export type PollOption = PollOptionBase & {
  id: string;
  /** 获得的累计票数 */
  votes_count: number;
};
