/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { PollAllOf } from './pollAllOf';
import type { PollBase } from './pollBase';

export type Poll = PollBase & PollAllOf;
