/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { PollOptionAllOf } from './pollOptionAllOf';
import type { PollOptionBase } from './pollOptionBase';

export type PollOption = PollOptionBase & PollOptionAllOf;
