/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { LikeStatus } from './likeStatus';
import type { PollOption } from './pollOption';
import type { PollVote } from './pollVote';

export type PollAllOf = {
  id: string;
  options: PollOption[];
  /** 参与投票的用户数 */
  participants_count: number;
  /** 总投票数 */
  total_votes_count: number;
  likes_count: number;
  /** 当前用户已投票的选项及票数 */
  my_votes: PollVote[];
  like_status: LikeStatus;
  created_by: string;
  created_at: Date;
};
