/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type PollOptionAllOf = {
  id: string;
  /** 获得的累计票数 */
  votes_count?: number;
};
