/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from './category.ts';
import type { LocalizedText } from './localizedText.ts';

export interface PollBase {
  public: boolean;
  title: LocalizedText;
  description?: LocalizedText;
  category: Category;
  tags?: string[];
  start_at: Date;
  expire_at?: Date;
  votes_per_user: number;
  votes_per_option: number;
}
