/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 点赞状态：1=点赞，0=取消操作，-1=点踩
 */
export type PostLikeVoteBodyLike = (typeof PostLikeVoteBodyLike)[keyof typeof PostLikeVoteBodyLike];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostLikeVoteBodyLike = {
  NUMBER_1: 1,
  NUMBER_0: 0,
  NUMBER_MINUS_1: -1,
} as const;
