/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type PostVoteBody = {
  option_ids: string[];
  /** 是否匿名投票 */
  anonymous?: boolean;
};
