/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type PostRegisterUserBody = {
  email: string;
  password: string;
  /** Preferred language code (e.g., "en", "zh") */
  language?: string;
};
