/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type PostSubmitAnswerBody = {
  selected_option_ids: string[];
  time_spent: number;
  exam_id?: string;
};
