/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { PostLikeQuestionBodyLike } from './postLikeQuestionBodyLike';

export type PostLikeQuestionBody = {
  /** 点赞状态：1=点赞，0=取消操作，-1=点踩 */
  like: PostLikeQuestionBodyLike;
};
