/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type PostVoteBodyOptionsItem = {
  /** 选项ID */
  option_id: string;
  /**
   * 给该选项投的票数
   * @minimum 1
   */
  votes: number;
};
