/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 点赞状态：1=点赞，0=取消操作，-1=点踩
 */
export type PostLikeQuestionBodyLike =
  (typeof PostLikeQuestionBodyLike)[keyof typeof PostLikeQuestionBodyLike];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostLikeQuestionBodyLike = {
  NUMBER_1: 1,
  NUMBER_0: 0,
  NUMBER_MINUS_1: -1,
} as const;
