/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { PollVote } from './pollVote.ts';

export type PostVotePollBody = {
  /** 投票选项列表，每个选项可以投不同数量的票 */
  options: PollVote[];
  /** 是否匿名投票 */
  anonymous?: boolean;
};
