/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type QuestionOptionAllOf = {
  id: string;
  /** 选中次数 */
  selected_count: number;
  /** 是否为正确答案 */
  is_answer?: boolean;
};
