/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { DateTime } from 'luxon';
import type { QuestionCategory } from './questionCategory';
import type { QuestionDifficulty } from './questionDifficulty';
import type { QuestionLikeStatus } from './questionLikeStatus';
import type { QuestionOption } from './questionOption';
import type { QuestionType } from './questionType';

export interface Question {
  id: string;
  /** 是否公开可见 */
  public: boolean;
  /** 是否已经通过了 */
  solved?: boolean;
  /** 点赞状态，1=已点赞，-1=已点踩，0=未操作 */
  likeStatus?: QuestionLikeStatus;
  question_type: QuestionType;
  category: QuestionCategory;
  difficulty: QuestionDifficulty;
  /** 支持的多语言列表 */
  languages: string[];
  question_text: string;
  options: QuestionOption[];
  explanation?: string;
  /** 总答题人数 */
  answer_count?: number;
  /** 总答对人数 */
  correct_count?: number;
  /** 点赞数 */
  likes?: number;
  created_by: string;
  created_at: DateTime;
}
