/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionQuestionType } from './questionQuestionType';

export interface Question {
  id: number;
  question_text: string;
  question_type: QuestionQuestionType;
  options?: string[];
  correct_answer: string;
  explanation?: string;
  points: number;
  order_index: number;
}
