/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 题目类型
 */
export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionType = {
  single_choice: 'single_choice',
  multiple_choice: 'multiple_choice',
  true_false: 'true_false',
} as const;
