/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { QuestionAllOf } from './questionAllOf';
import type { QuestionBase } from './questionBase';

export type Question = QuestionBase & QuestionAllOf;
