/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { LocalizedText } from './localizedText.ts';
import type { OptionType } from './optionType.ts';

export interface QuestionOptionBase {
  option_type: OptionType;
  text?: LocalizedText;
  media_url?: string;
}
