/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type QuestionQuestionType = typeof QuestionQuestionType[keyof typeof QuestionQuestionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionQuestionType = {
  multiple_choice: 'multiple_choice',
  true_false: 'true_false',
  fill_in_blank: 'fill_in_blank',
} as const;
