/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionOptionsType } from './questionOptionsType';

export type QuestionOptions = {
  /** 选项类型 */
  type: QuestionOptionsType;
  /** 选项文本 */
  text?: string;
  /** 选项图片URL */
  image?: string;
};
