/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 点赞状态，1=已点赞，-1=已点踩，0=未操作
 */
export type QuestionLikeStatus = (typeof QuestionLikeStatus)[keyof typeof QuestionLikeStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionLikeStatus = {
  NUMBER_1: 1,
  NUMBER_0: 0,
  NUMBER_MINUS_1: -1,
} as const;
