/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionTranslationOptionsItem } from './questionTranslationOptionsItem';

export interface QuestionTranslation {
  question_text: string;
  explanation: string;
  options: QuestionTranslationOptionsItem[];
}
