/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { QuestionOptionType } from './questionOptionType';

export interface QuestionOption {
  id: string;
  /** 选项类型 */
  type: QuestionOptionType;
  /** 选项文本 */
  text?: string;
  /** 选项图片URL */
  image?: string;
  /** 是否为正确答案 */
  is_answer?: boolean;
  /** 选中次数 */
  count?: number;
}
