/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 题目分类
 */
export type QuestionCategory = (typeof QuestionCategory)[keyof typeof QuestionCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionCategory = {
  character: 'character',
  weapon: 'weapon',
  artifact: 'artifact',
  lore: 'lore',
  gameplay: 'gameplay',
  world: 'world',
  combat: 'combat',
  music: 'music',
  statistics: 'statistics',
  fun: 'fun',
  other: 'other',
} as const;
