/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from './category.ts';
import type { Difficulty } from './difficulty.ts';
import type { LocalizedText } from './localizedText.ts';
import type { QuestionType } from './questionType.ts';

export interface QuestionBase {
  /** 是否公开可见 */
  public: boolean;
  question_type: QuestionType;
  category: Category;
  difficulty: Difficulty;
  question_text: LocalizedText;
  explanation?: LocalizedText;
}
