/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { QuestionCategory } from './questionCategory';
import type { QuestionDifficulty } from './questionDifficulty';
import type { QuestionType } from './questionType';
import type { QuestionWithAnswerTranslationsItem } from './questionWithAnswerTranslationsItem';

export interface QuestionWithAnswer {
  public: boolean;
  question_type: QuestionType;
  category: QuestionCategory;
  difficulty: QuestionDifficulty;
  translations: QuestionWithAnswerTranslationsItem[];
}
