/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { Category } from './category';
import type { Difficulty } from './difficulty';
import type { LocalizedText } from './localizedText';
import type { QuestionType } from './questionType';

export interface QuestionBase {
  /** 是否公开可见 */
  public: boolean;
  question_type: QuestionType;
  category: Category;
  difficulty: Difficulty;
  question_text: LocalizedText;
  explanation?: LocalizedText;
}
