/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { LikeStatus } from './likeStatus';
import type { QuestionOption } from './questionOption';

export type QuestionAllOf = {
  id: string;
  options: QuestionOption[];
  /** 是否已经通过了 */
  solved: boolean;
  like_status: LikeStatus;
  /** 总答题人数 */
  answers_count: number;
  /** 总答对人数 */
  correct_answers_count: number;
  /** 点赞数 */
  likes_count: number;
  created_by: string;
  created_at: Date;
};
