/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type QuestionQuestionType = (typeof QuestionQuestionType)[keyof typeof QuestionQuestionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionQuestionType = {
  single_choice: 'single_choice',
  multiple_choice: 'multiple_choice',
  true_false: 'true_false',
} as const;
