/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 选项类型
 */
export type QuestionOptionType = (typeof QuestionOptionType)[keyof typeof QuestionOptionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionOptionType = {
  text: 'text',
  image: 'image',
} as const;
