/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type QuizCategory = (typeof QuizCategory)[keyof typeof QuizCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuizCategory = {
  lore: 'lore',
  characters: 'characters',
  world: 'world',
  weapons: 'weapons',
  artifacts: 'artifacts',
  gameplay: 'gameplay',
  combat: 'combat',
  music: 'music',
  statistics: 'statistics',
  fun: 'fun',
  other: 'other',
} as const;
