/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type QuizDifficulty = typeof QuizDifficulty[keyof typeof QuizDifficulty];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuizDifficulty = {
  easy: 'easy',
  medium: 'medium',
  hard: 'hard',
} as const;
