/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { QuizCategory } from './quizCategory';
import type { QuizDifficulty } from './quizDifficulty';
import type { Question } from './question';

export interface Quiz {
  id: number;
  title: string;
  description?: string;
  category: QuizCategory;
  difficulty: QuizDifficulty;
  questions: Question[];
  /** Time limit in seconds */
  time_limit?: number;
  created_by: number;
  created_at: Date;
  updated_at: Date;
}
