/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type UpdateQuizRequestCategory =
  (typeof UpdateQuizRequestCategory)[keyof typeof UpdateQuizRequestCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateQuizRequestCategory = {
  characters: 'characters',
  weapons: 'weapons',
  artifacts: 'artifacts',
  lore: 'lore',
  gameplay: 'gameplay',
} as const;
