/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { CreateQuestionRequest } from './createQuestionRequest';
import type { UpdateQuizRequestCategory } from './updateQuizRequestCategory';
import type { UpdateQuizRequestDifficulty } from './updateQuizRequestDifficulty';

export interface UpdateQuizRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  /** @maxLength 1000 */
  description?: string;
  category?: UpdateQuizRequestCategory;
  difficulty?: UpdateQuizRequestDifficulty;
  /** @minItems 1 */
  questions?: CreateQuestionRequest[];
  /**
   * @minimum 30
   * @maximum 3600
   */
  time_limit?: number;
}
