/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Visibility } from './visibility.ts';

export interface UserPrivacy {
  email_visibility: Visibility;
  birthday_visibility: Visibility;
  gender_visibility: Visibility;
  country_visibility: Visibility;
}
