/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  uuid: string;
  nickname: string;
  avatar_url: string;
  country: string;
  language?: string;
  ip: string;
  total_answers: number;
  correct_answers: number;
  questions_created: number;
  votes: number;
  /** 该用户创建的所有题目获得的点赞总数，用于创作达人榜按点赞率排序 */
  likes_received?: number;
  registered_at: Date;
  last_login_at: Date;
  registered_ip?: string;
  last_login_ip?: string;
}
