/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { UserBase } from './userBase';
import type { UserProfile } from './userProfile';
import type { UserStats } from './userStats';

export type UserPublic = UserBase & UserProfile & UserStats;
