/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Visibility } from './visibility';

export interface UserPrivacy {
  email_visibility: Visibility;
  birthday_visibility: Visibility;
  gender_visibility: Visibility;
  country_visibility: Visibility;
}
