/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { UserPrivacy } from './userPrivacy.ts';
import type { UserPublic } from './userPublic.ts';
import type { UserSecurity } from './userSecurity.ts';

export type UserPrivate = UserPublic &
  UserPrivacy &
  UserSecurity &
  unknown &
  Required<Pick<UserPublic & UserPrivacy & UserSecurity & unknown, 'email'>>;
