/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export interface UserBase {
  uuid: string;
  nickname: string;
  avatar_url: string;
  bio: string;
  registered_at: Date;
}
