/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export interface UserStats {
  total_answers: number;
  correct_answers: number;
  questions_created: number;
  polls_created: number;
  likes_received: number;
}
