/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export interface UserSecurity {
  email_verified: boolean;
  registered_ip: string;
  last_login_at: Date;
  last_login_ip?: string;
}
