/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  uuid: string;
  nickname: string;
  avatar_url: string;
  country: string;
  language?: string;
  ip: string;
  total_answers: number;
  correct_answers: number;
  questions_created: number;
  votes: number;
  registered_at: Date;
  last_login_at: Date;
}
