/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type UserSexuality = (typeof UserSexuality)[keyof typeof UserSexuality];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSexuality = {
  male: 'male',
  female: 'female',
  other: 'other',
} as const;
