/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { UserPrivacy } from './userPrivacy';
import type { UserPublic } from './userPublic';
import type { UserSecurity } from './userSecurity';

export type UserPrivate = UserPublic & UserPrivacy & UserSecurity;
