/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { Gender } from './gender';

export interface UserProfile {
  email?: string;
  gender?: Gender;
  country?: string;
  language: string;
  birthday?: Date;
}
