/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { UserBase } from './userBase.ts';
import type { UserProfile } from './userProfile.ts';
import type { UserStats } from './userStats.ts';

export type UserPublic = UserBase & UserProfile & UserStats;
