/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type Visibility = (typeof Visibility)[keyof typeof Visibility];

export const Visibility = {
  public: 'public',
  private: 'private',
} as const;
