/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { QuestionCategory } from './questionCategory';
import type { VoteOption } from './voteOption';
import type { VoteWithOptionDescription } from './voteWithOptionDescription';
import type { VoteWithOptionTitle } from './voteWithOptionTitle';

export interface VoteWithOption {
  /** 是否公开可见(需要密码才能参与投票) */
  public: boolean;
  /** 投票密码 */
  password?: string;
  /** 多语言标题 */
  title: VoteWithOptionTitle;
  /** 多语言描述 */
  description?: VoteWithOptionDescription;
  category: QuestionCategory;
  tags?: string[];
  start_at: Date;
  expire_at?: Date;
  /** 每个用户最多可投票数 */
  votes_per_user: number;
  /** 每个选项的最大可投票数，0表示无限制 */
  votes_per_option?: number;
  options: VoteOption[];
}
