/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 选项类型（文本、图片、音乐）
 */
export type VoteOptionType = (typeof VoteOptionType)[keyof typeof VoteOptionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoteOptionType = {
  text: 'text',
  image: 'image',
  music: 'music',
} as const;
