/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 点赞状态：-1踩, 0未操作, 1赞
 */
export type VoteLikeStatus = (typeof VoteLikeStatus)[keyof typeof VoteLikeStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoteLikeStatus = {
  NUMBER_MINUS_1: -1,
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
