/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

export type VoteOptionType = (typeof VoteOptionType)[keyof typeof VoteOptionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoteOptionType = {
  text: 'text',
  image: 'image',
  music: 'music',
} as const;
