/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { QuestionCategory } from './questionCategory';
import type { VoteDescription } from './voteDescription';
import type { VoteLikeStatus } from './voteLikeStatus';
import type { VoteOption } from './voteOption';
import type { VoteSubmissionOption } from './voteSubmissionOption';
import type { VoteTitle } from './voteTitle';

export interface Vote {
  id: string;
  public: boolean;
  /** 多语言标题 */
  title: VoteTitle;
  /** 多语言描述 */
  description?: VoteDescription;
  category: QuestionCategory;
  tags?: string[];
  start_at: Date;
  expire_at?: Date;
  /** 投票是否已过期 */
  expired: boolean;
  /** 当前用户是否已参与投票 */
  voted: boolean;
  /** 当前用户已投票的选项及票数 */
  voted_options: VoteSubmissionOption[];
  /** 每个用户最多可投票数 */
  votes_per_user: number;
  /** 每个选项的最大可投票数，0表示无限制 */
  votes_per_option: number;
  options: VoteOption[];
  /** 参与投票的用户数 */
  participants?: number;
  /** 总投票数 */
  total_votes?: number;
  created_by: string;
  created_at: Date;
  likes?: number;
  /** 点赞状态：-1踩, 0未操作, 1赞 */
  likeStatus?: VoteLikeStatus;
}
