/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { VoteOption } from './voteOption';

export interface Vote {
  id: string;
  public: boolean;
  title: string;
  description?: string;
  created_by: string;
  created_at?: Date;
  expires_at?: Date;
  expired: boolean;
  votes_per_user: number;
  options: VoteOption[];
  participants?: number;
  total_votes?: number;
}
