/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { VoteOptionText } from './voteOptionText';
import type { VoteOptionType } from './voteOptionType';

export interface VoteOption {
  id?: string;
  /** 选项类型（文本、图片、音乐） */
  type: VoteOptionType;
  /** 选项文本 */
  text?: VoteOptionText;
  /** 选项图片URL */
  image_url?: string;
  /** 选项音乐URL */
  music_url?: string;
  /** 选项描述 */
  description?: string;
  /** 获得的累计票数 */
  votes?: number;
}
