/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 当前用户已投票的选项及票数，key为选项ID
 */
export type VoteVotedOptions = { [key: string]: number };
