/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 投票时单个选项的投票信息
 */
export interface VoteSubmissionOption {
  /** 选项ID */
  option_id: string;
  /**
   * 给该选项投的票数
   * @minimum 0
   */
  votes: number;
}
