/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

/**
 * 多语言描述
 */
export type VoteWithOptionDescription = { [key: string]: string };
