/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */
import type { VoteOptionType } from './voteOptionType';

export interface VoteOption {
  id: string;
  type: VoteOptionType;
  text?: string;
  image_url?: string;
  music_url?: string;
  votes?: number;
}
