/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { Arguments, Key, SWRConfiguration } from 'swr';
import useSwr from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';
import useSWRMutation from 'swr/mutation';

import type {
  AuthResponse,
  BadRequestResponse,
  CreatePollRequest,
  CreateQuestionRequest,
  Exam,
  GetExams200,
  GetExamsParams,
  GetHomeParams,
  GetPolls200,
  GetPollsParams,
  GetQuestions200,
  GetQuestionsParams,
  GetUserPolls200,
  GetUserPollsParams,
  GetUserQuestions200,
  GetUserQuestionsParams,
  GetUsers200,
  GetUsersParams,
  HomePageData,
  InternalServerErrorResponse,
  NotFoundResponse,
  Poll,
  PostChangePasswordBody,
  PostForgotPasswordBody,
  PostLikeExamBody,
  PostLikePollBody,
  PostLikeQuestionBody,
  PostLoginUserBody,
  PostRegisterUserBody,
  PostResetPasswordBody,
  PostSendVerificationEmailBody,
  PostSubmitAnswer200,
  PostSubmitAnswerBody,
  PostVerifyEmailBody,
  PostVotePollBody,
  Question,
  QuestionSubmission,
  RecentSubmission,
  UnauthorizedResponse,
  UserPrivate,
  UserPublic,
} from './dto';

import { Fetcher } from './fetcher/fetcher.ts';

export type postRegisterUserResponse201 = {
  data: AuthResponse;
  status: 201;
};

export type postRegisterUserResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postRegisterUserResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postRegisterUserResponseSuccess = postRegisterUserResponse201 & {
  headers: Headers;
};
export type postRegisterUserResponseError = (
  | postRegisterUserResponse400
  | postRegisterUserResponse500
) & {
  headers: Headers;
};

export type postRegisterUserResponse =
  | postRegisterUserResponseSuccess
  | postRegisterUserResponseError;

export const getPostRegisterUserUrl = () => {
  return `/auth/register`;
};

/**
 * @summary Register a new user
 */
export const postRegisterUser = async (
  postRegisterUserBody: PostRegisterUserBody,
  options?: RequestInit,
): Promise<postRegisterUserResponse> => {
  return Fetcher<postRegisterUserResponse>(getPostRegisterUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postRegisterUserBody),
  });
};

export const getPostRegisterUserMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostRegisterUserBody }) => {
    return postRegisterUser(arg);
  };
};
export const getPostRegisterUserMutationKey = () => [`/auth/register`] as const;

export type PostRegisterUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRegisterUser>>
>;

/**
 * @summary Register a new user
 */
export const usePostRegisterUser = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postRegisterUser>>,
    TError,
    Key,
    PostRegisterUserBody,
    Awaited<ReturnType<typeof postRegisterUser>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostRegisterUserMutationKey();
  const swrFn = getPostRegisterUserMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postLoginUserResponse200 = {
  data: AuthResponse;
  status: 200;
};

export type postLoginUserResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postLoginUserResponse401 = {
  data: undefined;
  status: 401;
};

export type postLoginUserResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postLoginUserResponseSuccess = postLoginUserResponse200 & {
  headers: Headers;
};
export type postLoginUserResponseError = (
  | postLoginUserResponse400
  | postLoginUserResponse401
  | postLoginUserResponse500
) & {
  headers: Headers;
};

export type postLoginUserResponse = postLoginUserResponseSuccess | postLoginUserResponseError;

export const getPostLoginUserUrl = () => {
  return `/auth/login`;
};

/**
 * @summary Login user
 */
export const postLoginUser = async (
  postLoginUserBody: PostLoginUserBody,
  options?: RequestInit,
): Promise<postLoginUserResponse> => {
  return Fetcher<postLoginUserResponse>(getPostLoginUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postLoginUserBody),
  });
};

export const getPostLoginUserMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostLoginUserBody }) => {
    return postLoginUser(arg);
  };
};
export const getPostLoginUserMutationKey = () => [`/auth/login`] as const;

export type PostLoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof postLoginUser>>>;

/**
 * @summary Login user
 */
export const usePostLoginUser = <
  TError = BadRequestResponse | undefined | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postLoginUser>>,
    TError,
    Key,
    PostLoginUserBody,
    Awaited<ReturnType<typeof postLoginUser>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostLoginUserMutationKey();
  const swrFn = getPostLoginUserMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postForgotPasswordResponse200 = {
  data: undefined;
  status: 200;
};

export type postForgotPasswordResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postForgotPasswordResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postForgotPasswordResponseSuccess = postForgotPasswordResponse200 & {
  headers: Headers;
};
export type postForgotPasswordResponseError = (
  | postForgotPasswordResponse400
  | postForgotPasswordResponse500
) & {
  headers: Headers;
};

export type postForgotPasswordResponse =
  | postForgotPasswordResponseSuccess
  | postForgotPasswordResponseError;

export const getPostForgotPasswordUrl = () => {
  return `/auth/forgot-password`;
};

/**
 * @summary Request password reset
 */
export const postForgotPassword = async (
  postForgotPasswordBody: PostForgotPasswordBody,
  options?: RequestInit,
): Promise<postForgotPasswordResponse> => {
  return Fetcher<postForgotPasswordResponse>(getPostForgotPasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postForgotPasswordBody),
  });
};

export const getPostForgotPasswordMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostForgotPasswordBody }) => {
    return postForgotPassword(arg);
  };
};
export const getPostForgotPasswordMutationKey = () => [`/auth/forgot-password`] as const;

export type PostForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postForgotPassword>>
>;

/**
 * @summary Request password reset
 */
export const usePostForgotPassword = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postForgotPassword>>,
    TError,
    Key,
    PostForgotPasswordBody,
    Awaited<ReturnType<typeof postForgotPassword>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostForgotPasswordMutationKey();
  const swrFn = getPostForgotPasswordMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postResetPasswordResponse200 = {
  data: undefined;
  status: 200;
};

export type postResetPasswordResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postResetPasswordResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postResetPasswordResponseSuccess = postResetPasswordResponse200 & {
  headers: Headers;
};
export type postResetPasswordResponseError = (
  | postResetPasswordResponse400
  | postResetPasswordResponse500
) & {
  headers: Headers;
};

export type postResetPasswordResponse =
  | postResetPasswordResponseSuccess
  | postResetPasswordResponseError;

export const getPostResetPasswordUrl = () => {
  return `/auth/reset-password`;
};

/**
 * @summary Reset password
 */
export const postResetPassword = async (
  postResetPasswordBody: PostResetPasswordBody,
  options?: RequestInit,
): Promise<postResetPasswordResponse> => {
  return Fetcher<postResetPasswordResponse>(getPostResetPasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postResetPasswordBody),
  });
};

export const getPostResetPasswordMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostResetPasswordBody }) => {
    return postResetPassword(arg);
  };
};
export const getPostResetPasswordMutationKey = () => [`/auth/reset-password`] as const;

export type PostResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postResetPassword>>
>;

/**
 * @summary Reset password
 */
export const usePostResetPassword = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postResetPassword>>,
    TError,
    Key,
    PostResetPasswordBody,
    Awaited<ReturnType<typeof postResetPassword>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostResetPasswordMutationKey();
  const swrFn = getPostResetPasswordMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postChangePasswordResponse200 = {
  data: undefined;
  status: 200;
};

export type postChangePasswordResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postChangePasswordResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postChangePasswordResponseSuccess = postChangePasswordResponse200 & {
  headers: Headers;
};
export type postChangePasswordResponseError = (
  | postChangePasswordResponse400
  | postChangePasswordResponse500
) & {
  headers: Headers;
};

export type postChangePasswordResponse =
  | postChangePasswordResponseSuccess
  | postChangePasswordResponseError;

export const getPostChangePasswordUrl = () => {
  return `/auth/change-password`;
};

/**
 * @summary Change password
 */
export const postChangePassword = async (
  postChangePasswordBody: PostChangePasswordBody,
  options?: RequestInit,
): Promise<postChangePasswordResponse> => {
  return Fetcher<postChangePasswordResponse>(getPostChangePasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postChangePasswordBody),
  });
};

export const getPostChangePasswordMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostChangePasswordBody }) => {
    return postChangePassword(arg);
  };
};
export const getPostChangePasswordMutationKey = () => [`/auth/change-password`] as const;

export type PostChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postChangePassword>>
>;

/**
 * @summary Change password
 */
export const usePostChangePassword = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postChangePassword>>,
    TError,
    Key,
    PostChangePasswordBody,
    Awaited<ReturnType<typeof postChangePassword>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostChangePasswordMutationKey();
  const swrFn = getPostChangePasswordMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postVerifyEmailResponse200 = {
  data: undefined;
  status: 200;
};

export type postVerifyEmailResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postVerifyEmailResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postVerifyEmailResponseSuccess = postVerifyEmailResponse200 & {
  headers: Headers;
};
export type postVerifyEmailResponseError = (
  | postVerifyEmailResponse400
  | postVerifyEmailResponse500
) & {
  headers: Headers;
};

export type postVerifyEmailResponse = postVerifyEmailResponseSuccess | postVerifyEmailResponseError;

export const getPostVerifyEmailUrl = () => {
  return `/auth/verify-email`;
};

/**
 * @summary Verify email address
 */
export const postVerifyEmail = async (
  postVerifyEmailBody: PostVerifyEmailBody,
  options?: RequestInit,
): Promise<postVerifyEmailResponse> => {
  return Fetcher<postVerifyEmailResponse>(getPostVerifyEmailUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postVerifyEmailBody),
  });
};

export const getPostVerifyEmailMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostVerifyEmailBody }) => {
    return postVerifyEmail(arg);
  };
};
export const getPostVerifyEmailMutationKey = () => [`/auth/verify-email`] as const;

export type PostVerifyEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof postVerifyEmail>>
>;

/**
 * @summary Verify email address
 */
export const usePostVerifyEmail = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postVerifyEmail>>,
    TError,
    Key,
    PostVerifyEmailBody,
    Awaited<ReturnType<typeof postVerifyEmail>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostVerifyEmailMutationKey();
  const swrFn = getPostVerifyEmailMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postSendVerificationEmailResponse200 = {
  data: undefined;
  status: 200;
};

export type postSendVerificationEmailResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postSendVerificationEmailResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postSendVerificationEmailResponseSuccess = postSendVerificationEmailResponse200 & {
  headers: Headers;
};
export type postSendVerificationEmailResponseError = (
  | postSendVerificationEmailResponse400
  | postSendVerificationEmailResponse500
) & {
  headers: Headers;
};

export type postSendVerificationEmailResponse =
  | postSendVerificationEmailResponseSuccess
  | postSendVerificationEmailResponseError;

export const getPostSendVerificationEmailUrl = () => {
  return `/auth/send-verification-email`;
};

/**
 * Sends a email with a verification token link to the user.
 * @summary Send verification email
 */
export const postSendVerificationEmail = async (
  postSendVerificationEmailBody: PostSendVerificationEmailBody,
  options?: RequestInit,
): Promise<postSendVerificationEmailResponse> => {
  return Fetcher<postSendVerificationEmailResponse>(getPostSendVerificationEmailUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postSendVerificationEmailBody),
  });
};

export const getPostSendVerificationEmailMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostSendVerificationEmailBody }) => {
    return postSendVerificationEmail(arg);
  };
};
export const getPostSendVerificationEmailMutationKey = () =>
  [`/auth/send-verification-email`] as const;

export type PostSendVerificationEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSendVerificationEmail>>
>;

/**
 * @summary Send verification email
 */
export const usePostSendVerificationEmail = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postSendVerificationEmail>>,
    TError,
    Key,
    PostSendVerificationEmailBody,
    Awaited<ReturnType<typeof postSendVerificationEmail>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostSendVerificationEmailMutationKey();
  const swrFn = getPostSendVerificationEmailMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getCurrentUserResponse200 = {
  data: UserPrivate;
  status: 200;
};

export type getCurrentUserResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getCurrentUserResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getCurrentUserResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getCurrentUserResponseSuccess = getCurrentUserResponse200 & {
  headers: Headers;
};
export type getCurrentUserResponseError = (
  | getCurrentUserResponse400
  | getCurrentUserResponse401
  | getCurrentUserResponse500
) & {
  headers: Headers;
};

export type getCurrentUserResponse = getCurrentUserResponseSuccess | getCurrentUserResponseError;

export const getGetCurrentUserUrl = () => {
  return `/auth/me`;
};

/**
 * @summary 获取当前用户信息
 */
export const getCurrentUser = async (options?: RequestInit): Promise<getCurrentUserResponse> => {
  return Fetcher<getCurrentUserResponse>(getGetCurrentUserUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetCurrentUserKey = () => [`/auth/me`] as const;

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>;

/**
 * @summary 获取当前用户信息
 */
export const useGetCurrentUser = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getCurrentUser>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
}) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetCurrentUserKey() : null));
  const swrFn = () => getCurrentUser();

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type updateUserResponse200 = {
  data: UserPrivate;
  status: 200;
};

export type updateUserResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateUserResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateUserResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type updateUserResponseSuccess = updateUserResponse200 & {
  headers: Headers;
};
export type updateUserResponseError = (
  | updateUserResponse400
  | updateUserResponse401
  | updateUserResponse500
) & {
  headers: Headers;
};

export type updateUserResponse = updateUserResponseSuccess | updateUserResponseError;

export const getUpdateUserUrl = () => {
  return `/auth/me`;
};

/**
 * @summary Update current user
 */
export const updateUser = async (
  userPrivate: UserPrivate,
  options?: RequestInit,
): Promise<updateUserResponse> => {
  return Fetcher<updateUserResponse>(getUpdateUserUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userPrivate),
  });
};

export const getUpdateUserMutationFetcher = () => {
  return (_: Key, { arg }: { arg: UserPrivate }) => {
    return updateUser(arg);
  };
};
export const getUpdateUserMutationKey = () => [`/auth/me`] as const;

export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>;

/**
 * @summary Update current user
 */
export const useUpdateUser = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    Key,
    UserPrivate,
    Awaited<ReturnType<typeof updateUser>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateUserMutationKey();
  const swrFn = getUpdateUserMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type deleteUserResponse204 = {
  data: undefined;
  status: 204;
};

export type deleteUserResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type deleteUserResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type deleteUserResponseSuccess = deleteUserResponse204 & {
  headers: Headers;
};
export type deleteUserResponseError = (deleteUserResponse401 | deleteUserResponse500) & {
  headers: Headers;
};

export type deleteUserResponse = deleteUserResponseSuccess | deleteUserResponseError;

export const getDeleteUserUrl = () => {
  return `/auth/me`;
};

/**
 * @summary Delete current user
 */
export const deleteUser = async (options?: RequestInit): Promise<deleteUserResponse> => {
  return Fetcher<deleteUserResponse>(getDeleteUserUrl(), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeleteUserMutationFetcher = () => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteUser();
  };
};
export const getDeleteUserMutationKey = () => [`/auth/me`] as const;

export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;

/**
 * @summary Delete current user
 */
export const useDeleteUser = <
  TError = UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof deleteUser>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteUserMutationKey();
  const swrFn = getDeleteUserMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getHomeResponse200 = {
  data: HomePageData;
  status: 200;
};

export type getHomeResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getHomeResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getHomeResponseSuccess = getHomeResponse200 & {
  headers: Headers;
};
export type getHomeResponseError = (getHomeResponse400 | getHomeResponse500) & {
  headers: Headers;
};

export type getHomeResponse = getHomeResponseSuccess | getHomeResponseError;

export const getGetHomeUrl = (params?: GetHomeParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/home?${stringifiedParams}` : `/home`;
};

/**
 * @summary Get homepage data
 */
export const getHome = async (
  params?: GetHomeParams,
  options?: RequestInit,
): Promise<getHomeResponse> => {
  return Fetcher<getHomeResponse>(getGetHomeUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetHomeKey = (params?: GetHomeParams) =>
  [`/home`, ...(params ? [params] : [])] as const;

export type GetHomeQueryResult = NonNullable<Awaited<ReturnType<typeof getHome>>>;

/**
 * @summary Get homepage data
 */
export const useGetHome = <TError = BadRequestResponse | InternalServerErrorResponse>(
  params?: GetHomeParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getHome>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetHomeKey(params) : null));
  const swrFn = () => getHome(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getUsersResponse200 = {
  data: GetUsers200;
  status: 200;
};

export type getUsersResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getUsersResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getUsersResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getUsersResponseSuccess = getUsersResponse200 & {
  headers: Headers;
};
export type getUsersResponseError = (
  | getUsersResponse400
  | getUsersResponse401
  | getUsersResponse500
) & {
  headers: Headers;
};

export type getUsersResponse = getUsersResponseSuccess | getUsersResponseError;

export const getGetUsersUrl = (params?: GetUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ['ids'];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users?${stringifiedParams}` : `/users`;
};

/**
 * @summary Get all users
 */
export const getUsers = async (
  params?: GetUsersParams,
  options?: RequestInit,
): Promise<getUsersResponse> => {
  return Fetcher<getUsersResponse>(getGetUsersUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetUsersKey = (params?: GetUsersParams) =>
  [`/users`, ...(params ? [params] : [])] as const;

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>;

/**
 * @summary Get all users
 */
export const useGetUsers = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(
  params?: GetUsersParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUsers>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetUsersKey(params) : null));
  const swrFn = () => getUsers(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getUserResponse200 = {
  data: UserPublic;
  status: 200;
};

export type getUserResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getUserResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getUserResponseSuccess = getUserResponse200 & {
  headers: Headers;
};
export type getUserResponseError = (getUserResponse404 | getUserResponse500) & {
  headers: Headers;
};

export type getUserResponse = getUserResponseSuccess | getUserResponseError;

export const getGetUserUrl = (id: string) => {
  return `/users/${id}`;
};

/**
 * @summary Get user by ID
 */
export const getUser = async (id: string, options?: RequestInit): Promise<getUserResponse> => {
  return Fetcher<getUserResponse>(getGetUserUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetUserKey = (id: string) => [`/users/${id}`] as const;

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>;

/**
 * @summary Get user by ID
 */
export const useGetUser = <TError = NotFoundResponse | InternalServerErrorResponse>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUser>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetUserKey(id) : null));
  const swrFn = () => getUser(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getUserPollsResponse200 = {
  data: GetUserPolls200;
  status: 200;
};

export type getUserPollsResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getUserPollsResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getUserPollsResponseSuccess = getUserPollsResponse200 & {
  headers: Headers;
};
export type getUserPollsResponseError = (getUserPollsResponse404 | getUserPollsResponse500) & {
  headers: Headers;
};

export type getUserPollsResponse = getUserPollsResponseSuccess | getUserPollsResponseError;

export const getGetUserPollsUrl = (id: string, params?: GetUserPollsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/users/${id}/polls?${stringifiedParams}`
    : `/users/${id}/polls`;
};

/**
 * @summary Get user's created polls
 */
export const getUserPolls = async (
  id: string,
  params?: GetUserPollsParams,
  options?: RequestInit,
): Promise<getUserPollsResponse> => {
  return Fetcher<getUserPollsResponse>(getGetUserPollsUrl(id, params), {
    ...options,
    method: 'GET',
  });
};

export const getGetUserPollsKey = (id: string, params?: GetUserPollsParams) =>
  [`/users/${id}/polls`, ...(params ? [params] : [])] as const;

export type GetUserPollsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserPolls>>>;

/**
 * @summary Get user's created polls
 */
export const useGetUserPolls = <TError = NotFoundResponse | InternalServerErrorResponse>(
  id: string,
  params?: GetUserPollsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUserPolls>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetUserPollsKey(id, params) : null));
  const swrFn = () => getUserPolls(id, params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getUserQuestionsResponse200 = {
  data: GetUserQuestions200;
  status: 200;
};

export type getUserQuestionsResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getUserQuestionsResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getUserQuestionsResponseSuccess = getUserQuestionsResponse200 & {
  headers: Headers;
};
export type getUserQuestionsResponseError = (
  | getUserQuestionsResponse404
  | getUserQuestionsResponse500
) & {
  headers: Headers;
};

export type getUserQuestionsResponse =
  | getUserQuestionsResponseSuccess
  | getUserQuestionsResponseError;

export const getGetUserQuestionsUrl = (id: string, params?: GetUserQuestionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/users/${id}/questions?${stringifiedParams}`
    : `/users/${id}/questions`;
};

/**
 * @summary Get user's created question
 */
export const getUserQuestions = async (
  id: string,
  params?: GetUserQuestionsParams,
  options?: RequestInit,
): Promise<getUserQuestionsResponse> => {
  return Fetcher<getUserQuestionsResponse>(getGetUserQuestionsUrl(id, params), {
    ...options,
    method: 'GET',
  });
};

export const getGetUserQuestionsKey = (id: string, params?: GetUserQuestionsParams) =>
  [`/users/${id}/questions`, ...(params ? [params] : [])] as const;

export type GetUserQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserQuestions>>>;

/**
 * @summary Get user's created question
 */
export const useGetUserQuestions = <TError = NotFoundResponse | InternalServerErrorResponse>(
  id: string,
  params?: GetUserQuestionsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUserQuestions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetUserQuestionsKey(id, params) : null));
  const swrFn = () => getUserQuestions(id, params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getQuestionsResponse200 = {
  data: GetQuestions200;
  status: 200;
};

export type getQuestionsResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getQuestionsResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getQuestionsResponseSuccess = getQuestionsResponse200 & {
  headers: Headers;
};
export type getQuestionsResponseError = (getQuestionsResponse400 | getQuestionsResponse500) & {
  headers: Headers;
};

export type getQuestionsResponse = getQuestionsResponseSuccess | getQuestionsResponseError;

export const getGetQuestionsUrl = (params?: GetQuestionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ['difficulty', 'language'];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/questions?${stringifiedParams}` : `/questions`;
};

/**
 * @summary Get all questions
 */
export const getQuestions = async (
  params?: GetQuestionsParams,
  options?: RequestInit,
): Promise<getQuestionsResponse> => {
  return Fetcher<getQuestionsResponse>(getGetQuestionsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetQuestionsKey = (params?: GetQuestionsParams) =>
  [`/questions`, ...(params ? [params] : [])] as const;

export type GetQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestions>>>;

/**
 * @summary Get all questions
 */
export const useGetQuestions = <TError = BadRequestResponse | InternalServerErrorResponse>(
  params?: GetQuestionsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getQuestions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetQuestionsKey(params) : null));
  const swrFn = () => getQuestions(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postCreateQuestionResponse201 = {
  data: CreateQuestionRequest;
  status: 201;
};

export type postCreateQuestionResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postCreateQuestionResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type postCreateQuestionResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postCreateQuestionResponseSuccess = postCreateQuestionResponse201 & {
  headers: Headers;
};
export type postCreateQuestionResponseError = (
  | postCreateQuestionResponse400
  | postCreateQuestionResponse401
  | postCreateQuestionResponse500
) & {
  headers: Headers;
};

export type postCreateQuestionResponse =
  | postCreateQuestionResponseSuccess
  | postCreateQuestionResponseError;

export const getPostCreateQuestionUrl = () => {
  return `/questions`;
};

/**
 * @summary Create a new question
 */
export const postCreateQuestion = async (
  createQuestionRequest: CreateQuestionRequest,
  options?: RequestInit,
): Promise<postCreateQuestionResponse> => {
  return Fetcher<postCreateQuestionResponse>(getPostCreateQuestionUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createQuestionRequest),
  });
};

export const getPostCreateQuestionMutationFetcher = () => {
  return (_: Key, { arg }: { arg: CreateQuestionRequest }) => {
    return postCreateQuestion(arg);
  };
};
export const getPostCreateQuestionMutationKey = () => [`/questions`] as const;

export type PostCreateQuestionMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateQuestion>>
>;

/**
 * @summary Create a new question
 */
export const usePostCreateQuestion = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postCreateQuestion>>,
    TError,
    Key,
    CreateQuestionRequest,
    Awaited<ReturnType<typeof postCreateQuestion>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostCreateQuestionMutationKey();
  const swrFn = getPostCreateQuestionMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getQuestionResponse200 = {
  data: Question;
  status: 200;
};

export type getQuestionResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getQuestionResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getQuestionResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getQuestionResponseSuccess = getQuestionResponse200 & {
  headers: Headers;
};
export type getQuestionResponseError = (
  | getQuestionResponse400
  | getQuestionResponse404
  | getQuestionResponse500
) & {
  headers: Headers;
};

export type getQuestionResponse = getQuestionResponseSuccess | getQuestionResponseError;

export const getGetQuestionUrl = (id: string) => {
  return `/questions/${id}`;
};

/**
 * @summary Get question by ID
 */
export const getQuestion = async (
  id: string,
  options?: RequestInit,
): Promise<getQuestionResponse> => {
  return Fetcher<getQuestionResponse>(getGetQuestionUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetQuestionKey = (id: string) => [`/questions/${id}`] as const;

export type GetQuestionQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestion>>>;

/**
 * @summary Get question by ID
 */
export const useGetQuestion = <
  TError = BadRequestResponse | NotFoundResponse | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getQuestion>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetQuestionKey(id) : null));
  const swrFn = () => getQuestion(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type updateQuestionResponse200 = {
  data: CreateQuestionRequest;
  status: 200;
};

export type updateQuestionResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateQuestionResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateQuestionResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type updateQuestionResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type updateQuestionResponseSuccess = updateQuestionResponse200 & {
  headers: Headers;
};
export type updateQuestionResponseError = (
  | updateQuestionResponse400
  | updateQuestionResponse401
  | updateQuestionResponse404
  | updateQuestionResponse500
) & {
  headers: Headers;
};

export type updateQuestionResponse = updateQuestionResponseSuccess | updateQuestionResponseError;

export const getUpdateQuestionUrl = (id: string) => {
  return `/questions/${id}`;
};

/**
 * @summary Update question
 */
export const updateQuestion = async (
  id: string,
  createQuestionRequest: CreateQuestionRequest,
  options?: RequestInit,
): Promise<updateQuestionResponse> => {
  return Fetcher<updateQuestionResponse>(getUpdateQuestionUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createQuestionRequest),
  });
};

export const getUpdateQuestionMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: CreateQuestionRequest }) => {
    return updateQuestion(id, arg);
  };
};
export const getUpdateQuestionMutationKey = (id: string) => [`/questions/${id}`] as const;

export type UpdateQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof updateQuestion>>>;

/**
 * @summary Update question
 */
export const useUpdateQuestion = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateQuestion>>,
      TError,
      Key,
      CreateQuestionRequest,
      Awaited<ReturnType<typeof updateQuestion>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateQuestionMutationKey(id);
  const swrFn = getUpdateQuestionMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type deleteQuestionResponse204 = {
  data: undefined;
  status: 204;
};

export type deleteQuestionResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type deleteQuestionResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type deleteQuestionResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type deleteQuestionResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type deleteQuestionResponseSuccess = deleteQuestionResponse204 & {
  headers: Headers;
};
export type deleteQuestionResponseError = (
  | deleteQuestionResponse400
  | deleteQuestionResponse401
  | deleteQuestionResponse404
  | deleteQuestionResponse500
) & {
  headers: Headers;
};

export type deleteQuestionResponse = deleteQuestionResponseSuccess | deleteQuestionResponseError;

export const getDeleteQuestionUrl = (id: string) => {
  return `/questions/${id}`;
};

/**
 * @summary Delete question
 */
export const deleteQuestion = async (
  id: string,
  options?: RequestInit,
): Promise<deleteQuestionResponse> => {
  return Fetcher<deleteQuestionResponse>(getDeleteQuestionUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeleteQuestionMutationFetcher = (id: string) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteQuestion(id);
  };
};
export const getDeleteQuestionMutationKey = (id: string) => [`/questions/${id}`] as const;

export type DeleteQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQuestion>>>;

/**
 * @summary Delete question
 */
export const useDeleteQuestion = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteQuestion>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteQuestion>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteQuestionMutationKey(id);
  const swrFn = getDeleteQuestionMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postSubmitAnswerResponse200 = {
  data: PostSubmitAnswer200;
  status: 200;
};

export type postSubmitAnswerResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postSubmitAnswerResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type postSubmitAnswerResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type postSubmitAnswerResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postSubmitAnswerResponseSuccess = postSubmitAnswerResponse200 & {
  headers: Headers;
};
export type postSubmitAnswerResponseError = (
  | postSubmitAnswerResponse400
  | postSubmitAnswerResponse401
  | postSubmitAnswerResponse404
  | postSubmitAnswerResponse500
) & {
  headers: Headers;
};

export type postSubmitAnswerResponse =
  | postSubmitAnswerResponseSuccess
  | postSubmitAnswerResponseError;

export const getPostSubmitAnswerUrl = (id: string) => {
  return `/questions/${id}/submit`;
};

/**
 * Submit user's answer for a specific question and get result
 * @summary Submit answer for a question
 */
export const postSubmitAnswer = async (
  id: string,
  postSubmitAnswerBody: PostSubmitAnswerBody,
  options?: RequestInit,
): Promise<postSubmitAnswerResponse> => {
  return Fetcher<postSubmitAnswerResponse>(getPostSubmitAnswerUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postSubmitAnswerBody),
  });
};

export const getPostSubmitAnswerMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostSubmitAnswerBody }) => {
    return postSubmitAnswer(id, arg);
  };
};
export const getPostSubmitAnswerMutationKey = (id: string) => [`/questions/${id}/submit`] as const;

export type PostSubmitAnswerMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSubmitAnswer>>
>;

/**
 * @summary Submit answer for a question
 */
export const usePostSubmitAnswer = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postSubmitAnswer>>,
      TError,
      Key,
      PostSubmitAnswerBody,
      Awaited<ReturnType<typeof postSubmitAnswer>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostSubmitAnswerMutationKey(id);
  const swrFn = getPostSubmitAnswerMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postLikeQuestionResponse201 = {
  data: undefined;
  status: 201;
};

export type postLikeQuestionResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postLikeQuestionResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type postLikeQuestionResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type postLikeQuestionResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postLikeQuestionResponseSuccess = postLikeQuestionResponse201 & {
  headers: Headers;
};
export type postLikeQuestionResponseError = (
  | postLikeQuestionResponse400
  | postLikeQuestionResponse401
  | postLikeQuestionResponse404
  | postLikeQuestionResponse500
) & {
  headers: Headers;
};

export type postLikeQuestionResponse =
  | postLikeQuestionResponseSuccess
  | postLikeQuestionResponseError;

export const getPostLikeQuestionUrl = (id: string) => {
  return `/questions/${id}/like`;
};

/**
 * Submit user's answer for a specific question and get result
 * @summary Like or dislike a question
 */
export const postLikeQuestion = async (
  id: string,
  postLikeQuestionBody: PostLikeQuestionBody,
  options?: RequestInit,
): Promise<postLikeQuestionResponse> => {
  return Fetcher<postLikeQuestionResponse>(getPostLikeQuestionUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postLikeQuestionBody),
  });
};

export const getPostLikeQuestionMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostLikeQuestionBody }) => {
    return postLikeQuestion(id, arg);
  };
};
export const getPostLikeQuestionMutationKey = (id: string) => [`/questions/${id}/like`] as const;

export type PostLikeQuestionMutationResult = NonNullable<
  Awaited<ReturnType<typeof postLikeQuestion>>
>;

/**
 * @summary Like or dislike a question
 */
export const usePostLikeQuestion = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postLikeQuestion>>,
      TError,
      Key,
      PostLikeQuestionBody,
      Awaited<ReturnType<typeof postLikeQuestion>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostLikeQuestionMutationKey(id);
  const swrFn = getPostLikeQuestionMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getQuestionMySubmissionsResponse200 = {
  data: QuestionSubmission[];
  status: 200;
};

export type getQuestionMySubmissionsResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getQuestionMySubmissionsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getQuestionMySubmissionsResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getQuestionMySubmissionsResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getQuestionMySubmissionsResponseSuccess = getQuestionMySubmissionsResponse200 & {
  headers: Headers;
};
export type getQuestionMySubmissionsResponseError = (
  | getQuestionMySubmissionsResponse400
  | getQuestionMySubmissionsResponse401
  | getQuestionMySubmissionsResponse404
  | getQuestionMySubmissionsResponse500
) & {
  headers: Headers;
};

export type getQuestionMySubmissionsResponse =
  | getQuestionMySubmissionsResponseSuccess
  | getQuestionMySubmissionsResponseError;

export const getGetQuestionMySubmissionsUrl = (id: string) => {
  return `/questions/${id}/my-answers`;
};

/**
 * Get current user's submission records for a specific question (up to 100 records)
 * @summary Get my submissions for a question
 */
export const getQuestionMySubmissions = async (
  id: string,
  options?: RequestInit,
): Promise<getQuestionMySubmissionsResponse> => {
  return Fetcher<getQuestionMySubmissionsResponse>(getGetQuestionMySubmissionsUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetQuestionMySubmissionsKey = (id: string) =>
  [`/questions/${id}/my-answers`] as const;

export type GetQuestionMySubmissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionMySubmissions>>
>;

/**
 * @summary Get my submissions for a question
 */
export const useGetQuestionMySubmissions = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getQuestionMySubmissions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetQuestionMySubmissionsKey(id) : null));
  const swrFn = () => getQuestionMySubmissions(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getQuestionRecentSubmissionsResponse200 = {
  data: RecentSubmission[];
  status: 200;
};

export type getQuestionRecentSubmissionsResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getQuestionRecentSubmissionsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getQuestionRecentSubmissionsResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getQuestionRecentSubmissionsResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getQuestionRecentSubmissionsResponseSuccess =
  getQuestionRecentSubmissionsResponse200 & {
    headers: Headers;
  };
export type getQuestionRecentSubmissionsResponseError = (
  | getQuestionRecentSubmissionsResponse400
  | getQuestionRecentSubmissionsResponse401
  | getQuestionRecentSubmissionsResponse404
  | getQuestionRecentSubmissionsResponse500
) & {
  headers: Headers;
};

export type getQuestionRecentSubmissionsResponse =
  | getQuestionRecentSubmissionsResponseSuccess
  | getQuestionRecentSubmissionsResponseError;

export const getGetQuestionRecentSubmissionsUrl = (id: string) => {
  return `/questions/${id}/recent`;
};

/**
 * Get recent submission records from other users for a specific question (up to 100 records)
 * @summary Get recent submissions from other users
 */
export const getQuestionRecentSubmissions = async (
  id: string,
  options?: RequestInit,
): Promise<getQuestionRecentSubmissionsResponse> => {
  return Fetcher<getQuestionRecentSubmissionsResponse>(getGetQuestionRecentSubmissionsUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetQuestionRecentSubmissionsKey = (id: string) =>
  [`/questions/${id}/recent`] as const;

export type GetQuestionRecentSubmissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionRecentSubmissions>>
>;

/**
 * @summary Get recent submissions from other users
 */
export const useGetQuestionRecentSubmissions = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getQuestionRecentSubmissions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetQuestionRecentSubmissionsKey(id) : null));
  const swrFn = () => getQuestionRecentSubmissions(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getExamsResponse200 = {
  data: GetExams200;
  status: 200;
};

export type getExamsResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getExamsResponseSuccess = getExamsResponse200 & {
  headers: Headers;
};
export type getExamsResponseError = getExamsResponse500 & {
  headers: Headers;
};

export type getExamsResponse = getExamsResponseSuccess | getExamsResponseError;

export const getGetExamsUrl = (params?: GetExamsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/exams?${stringifiedParams}` : `/exams`;
};

/**
 * @summary Get all exams
 */
export const getExams = async (
  params?: GetExamsParams,
  options?: RequestInit,
): Promise<getExamsResponse> => {
  return Fetcher<getExamsResponse>(getGetExamsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetExamsKey = (params?: GetExamsParams) =>
  [`/exams`, ...(params ? [params] : [])] as const;

export type GetExamsQueryResult = NonNullable<Awaited<ReturnType<typeof getExams>>>;

/**
 * @summary Get all exams
 */
export const useGetExams = <TError = InternalServerErrorResponse>(
  params?: GetExamsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getExams>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetExamsKey(params) : null));
  const swrFn = () => getExams(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postCreateExamResponse201 = {
  data: Exam;
  status: 201;
};

export type postCreateExamResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postCreateExamResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type postCreateExamResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postCreateExamResponseSuccess = postCreateExamResponse201 & {
  headers: Headers;
};
export type postCreateExamResponseError = (
  | postCreateExamResponse400
  | postCreateExamResponse401
  | postCreateExamResponse500
) & {
  headers: Headers;
};

export type postCreateExamResponse = postCreateExamResponseSuccess | postCreateExamResponseError;

export const getPostCreateExamUrl = () => {
  return `/exams`;
};

/**
 * @summary Create a new exam
 */
export const postCreateExam = async (
  exam: Exam,
  options?: RequestInit,
): Promise<postCreateExamResponse> => {
  return Fetcher<postCreateExamResponse>(getPostCreateExamUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exam),
  });
};

export const getPostCreateExamMutationFetcher = () => {
  return (_: Key, { arg }: { arg: Exam }) => {
    return postCreateExam(arg);
  };
};
export const getPostCreateExamMutationKey = () => [`/exams`] as const;

export type PostCreateExamMutationResult = NonNullable<Awaited<ReturnType<typeof postCreateExam>>>;

/**
 * @summary Create a new exam
 */
export const usePostCreateExam = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postCreateExam>>,
    TError,
    Key,
    Exam,
    Awaited<ReturnType<typeof postCreateExam>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostCreateExamMutationKey();
  const swrFn = getPostCreateExamMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getExamResponse200 = {
  data: Exam;
  status: 200;
};

export type getExamResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getExamResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getExamResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getExamResponseSuccess = getExamResponse200 & {
  headers: Headers;
};
export type getExamResponseError = (
  | getExamResponse400
  | getExamResponse404
  | getExamResponse500
) & {
  headers: Headers;
};

export type getExamResponse = getExamResponseSuccess | getExamResponseError;

export const getGetExamUrl = (id: string) => {
  return `/exams/${id}`;
};

/**
 * @summary Get exam by ID
 */
export const getExam = async (id: string, options?: RequestInit): Promise<getExamResponse> => {
  return Fetcher<getExamResponse>(getGetExamUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetExamKey = (id: string) => [`/exams/${id}`] as const;

export type GetExamQueryResult = NonNullable<Awaited<ReturnType<typeof getExam>>>;

/**
 * @summary Get exam by ID
 */
export const useGetExam = <
  TError = BadRequestResponse | NotFoundResponse | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getExam>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetExamKey(id) : null));
  const swrFn = () => getExam(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type updateExamResponse200 = {
  data: Exam;
  status: 200;
};

export type updateExamResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateExamResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateExamResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type updateExamResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type updateExamResponseSuccess = updateExamResponse200 & {
  headers: Headers;
};
export type updateExamResponseError = (
  | updateExamResponse400
  | updateExamResponse401
  | updateExamResponse404
  | updateExamResponse500
) & {
  headers: Headers;
};

export type updateExamResponse = updateExamResponseSuccess | updateExamResponseError;

export const getUpdateExamUrl = (id: string) => {
  return `/exams/${id}`;
};

/**
 * @summary Update exam
 */
export const updateExam = async (
  id: string,
  exam: Exam,
  options?: RequestInit,
): Promise<updateExamResponse> => {
  return Fetcher<updateExamResponse>(getUpdateExamUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exam),
  });
};

export const getUpdateExamMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: Exam }) => {
    return updateExam(id, arg);
  };
};
export const getUpdateExamMutationKey = (id: string) => [`/exams/${id}`] as const;

export type UpdateExamMutationResult = NonNullable<Awaited<ReturnType<typeof updateExam>>>;

/**
 * @summary Update exam
 */
export const useUpdateExam = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateExam>>,
      TError,
      Key,
      Exam,
      Awaited<ReturnType<typeof updateExam>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateExamMutationKey(id);
  const swrFn = getUpdateExamMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type deleteExamResponse204 = {
  data: undefined;
  status: 204;
};

export type deleteExamResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type deleteExamResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type deleteExamResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type deleteExamResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type deleteExamResponseSuccess = deleteExamResponse204 & {
  headers: Headers;
};
export type deleteExamResponseError = (
  | deleteExamResponse400
  | deleteExamResponse401
  | deleteExamResponse404
  | deleteExamResponse500
) & {
  headers: Headers;
};

export type deleteExamResponse = deleteExamResponseSuccess | deleteExamResponseError;

export const getDeleteExamUrl = (id: string) => {
  return `/exams/${id}`;
};

/**
 * @summary Delete exam
 */
export const deleteExam = async (
  id: string,
  options?: RequestInit,
): Promise<deleteExamResponse> => {
  return Fetcher<deleteExamResponse>(getDeleteExamUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeleteExamMutationFetcher = (id: string) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteExam(id);
  };
};
export const getDeleteExamMutationKey = (id: string) => [`/exams/${id}`] as const;

export type DeleteExamMutationResult = NonNullable<Awaited<ReturnType<typeof deleteExam>>>;

/**
 * @summary Delete exam
 */
export const useDeleteExam = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteExam>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteExam>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteExamMutationKey(id);
  const swrFn = getDeleteExamMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postLikeExamResponse201 = {
  data: undefined;
  status: 201;
};

export type postLikeExamResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postLikeExamResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type postLikeExamResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type postLikeExamResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postLikeExamResponseSuccess = postLikeExamResponse201 & {
  headers: Headers;
};
export type postLikeExamResponseError = (
  | postLikeExamResponse400
  | postLikeExamResponse401
  | postLikeExamResponse404
  | postLikeExamResponse500
) & {
  headers: Headers;
};

export type postLikeExamResponse = postLikeExamResponseSuccess | postLikeExamResponseError;

export const getPostLikeExamUrl = (id: string) => {
  return `/exams/${id}/like`;
};

/**
 * @summary 点赞测验
 */
export const postLikeExam = async (
  id: string,
  postLikeExamBody: PostLikeExamBody,
  options?: RequestInit,
): Promise<postLikeExamResponse> => {
  return Fetcher<postLikeExamResponse>(getPostLikeExamUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postLikeExamBody),
  });
};

export const getPostLikeExamMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostLikeExamBody }) => {
    return postLikeExam(id, arg);
  };
};
export const getPostLikeExamMutationKey = (id: string) => [`/exams/${id}/like`] as const;

export type PostLikeExamMutationResult = NonNullable<Awaited<ReturnType<typeof postLikeExam>>>;

/**
 * @summary 点赞测验
 */
export const usePostLikeExam = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postLikeExam>>,
      TError,
      Key,
      PostLikeExamBody,
      Awaited<ReturnType<typeof postLikeExam>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostLikeExamMutationKey(id);
  const swrFn = getPostLikeExamMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getPollsResponse200 = {
  data: GetPolls200;
  status: 200;
};

export type getPollsResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getPollsResponseSuccess = getPollsResponse200 & {
  headers: Headers;
};
export type getPollsResponseError = getPollsResponse500 & {
  headers: Headers;
};

export type getPollsResponse = getPollsResponseSuccess | getPollsResponseError;

export const getGetPollsUrl = (params?: GetPollsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ['language'];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/polls?${stringifiedParams}` : `/polls`;
};

/**
 * @summary Get all polls
 */
export const getPolls = async (
  params?: GetPollsParams,
  options?: RequestInit,
): Promise<getPollsResponse> => {
  return Fetcher<getPollsResponse>(getGetPollsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetPollsKey = (params?: GetPollsParams) =>
  [`/polls`, ...(params ? [params] : [])] as const;

export type GetPollsQueryResult = NonNullable<Awaited<ReturnType<typeof getPolls>>>;

/**
 * @summary Get all polls
 */
export const useGetPolls = <TError = InternalServerErrorResponse>(
  params?: GetPollsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getPolls>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetPollsKey(params) : null));
  const swrFn = () => getPolls(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postCreatePollResponse201 = {
  data: Poll;
  status: 201;
};

export type postCreatePollResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postCreatePollResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type postCreatePollResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postCreatePollResponseSuccess = postCreatePollResponse201 & {
  headers: Headers;
};
export type postCreatePollResponseError = (
  | postCreatePollResponse400
  | postCreatePollResponse401
  | postCreatePollResponse500
) & {
  headers: Headers;
};

export type postCreatePollResponse = postCreatePollResponseSuccess | postCreatePollResponseError;

export const getPostCreatePollUrl = () => {
  return `/polls`;
};

/**
 * @summary Create new poll
 */
export const postCreatePoll = async (
  createPollRequest: CreatePollRequest,
  options?: RequestInit,
): Promise<postCreatePollResponse> => {
  return Fetcher<postCreatePollResponse>(getPostCreatePollUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPollRequest),
  });
};

export const getPostCreatePollMutationFetcher = () => {
  return (_: Key, { arg }: { arg: CreatePollRequest }) => {
    return postCreatePoll(arg);
  };
};
export const getPostCreatePollMutationKey = () => [`/polls`] as const;

export type PostCreatePollMutationResult = NonNullable<Awaited<ReturnType<typeof postCreatePoll>>>;

/**
 * @summary Create new poll
 */
export const usePostCreatePoll = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postCreatePoll>>,
    TError,
    Key,
    CreatePollRequest,
    Awaited<ReturnType<typeof postCreatePoll>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostCreatePollMutationKey();
  const swrFn = getPostCreatePollMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type getPollResponse200 = {
  data: Poll;
  status: 200;
};

export type getPollResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type getPollResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getPollResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type getPollResponseSuccess = getPollResponse200 & {
  headers: Headers;
};
export type getPollResponseError = (
  | getPollResponse400
  | getPollResponse404
  | getPollResponse500
) & {
  headers: Headers;
};

export type getPollResponse = getPollResponseSuccess | getPollResponseError;

export const getGetPollUrl = (id: string) => {
  return `/polls/${id}`;
};

/**
 * @summary 获取投票详情（含当前结果）
 */
export const getPoll = async (id: string, options?: RequestInit): Promise<getPollResponse> => {
  return Fetcher<getPollResponse>(getGetPollUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetPollKey = (id: string) => [`/polls/${id}`] as const;

export type GetPollQueryResult = NonNullable<Awaited<ReturnType<typeof getPoll>>>;

/**
 * @summary 获取投票详情（含当前结果）
 */
export const useGetPoll = <
  TError = BadRequestResponse | NotFoundResponse | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getPoll>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && id !== null && id !== undefined;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetPollKey(id) : null));
  const swrFn = () => getPoll(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postLikePollResponse201 = {
  data: undefined;
  status: 201;
};

export type postLikePollResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postLikePollResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type postLikePollResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type postLikePollResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postLikePollResponseSuccess = postLikePollResponse201 & {
  headers: Headers;
};
export type postLikePollResponseError = (
  | postLikePollResponse400
  | postLikePollResponse401
  | postLikePollResponse404
  | postLikePollResponse500
) & {
  headers: Headers;
};

export type postLikePollResponse = postLikePollResponseSuccess | postLikePollResponseError;

export const getPostLikePollUrl = (id: string) => {
  return `/polls/${id}/like`;
};

/**
 * @summary 点赞投票
 */
export const postLikePoll = async (
  id: string,
  postLikePollBody: PostLikePollBody,
  options?: RequestInit,
): Promise<postLikePollResponse> => {
  return Fetcher<postLikePollResponse>(getPostLikePollUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postLikePollBody),
  });
};

export const getPostLikePollMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostLikePollBody }) => {
    return postLikePoll(id, arg);
  };
};
export const getPostLikePollMutationKey = (id: string) => [`/polls/${id}/like`] as const;

export type PostLikePollMutationResult = NonNullable<Awaited<ReturnType<typeof postLikePoll>>>;

/**
 * @summary 点赞投票
 */
export const usePostLikePoll = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postLikePoll>>,
      TError,
      Key,
      PostLikePollBody,
      Awaited<ReturnType<typeof postLikePoll>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostLikePollMutationKey(id);
  const swrFn = getPostLikePollMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type postVotePollResponse200 = {
  data: undefined;
  status: 200;
};

export type postVotePollResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postVotePollResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type postVotePollResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type postVotePollResponse500 = {
  data: InternalServerErrorResponse;
  status: 500;
};

export type postVotePollResponseSuccess = postVotePollResponse200 & {
  headers: Headers;
};
export type postVotePollResponseError = (
  | postVotePollResponse400
  | postVotePollResponse401
  | postVotePollResponse404
  | postVotePollResponse500
) & {
  headers: Headers;
};

export type postVotePollResponse = postVotePollResponseSuccess | postVotePollResponseError;

export const getPostVotePollUrl = (id: string) => {
  return `/polls/${id}/vote`;
};

/**
 * @summary 投票
 */
export const postVotePoll = async (
  id: string,
  postVotePollBody: PostVotePollBody,
  options?: RequestInit,
): Promise<postVotePollResponse> => {
  return Fetcher<postVotePollResponse>(getPostVotePollUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postVotePollBody),
  });
};

export const getPostVotePollMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostVotePollBody }) => {
    return postVotePoll(id, arg);
  };
};
export const getPostVotePollMutationKey = (id: string) => [`/polls/${id}/vote`] as const;

export type PostVotePollMutationResult = NonNullable<Awaited<ReturnType<typeof postVotePoll>>>;

/**
 * @summary 投票
 */
export const usePostVotePoll = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postVotePoll>>,
      TError,
      Key,
      PostVotePollBody,
      Awaited<ReturnType<typeof postVotePoll>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostVotePollMutationKey(id);
  const swrFn = getPostVotePollMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
