/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Genshin Quiz API
 * API for Genshin Impact Quiz Application
 * OpenAPI spec version: 1.0.0
 */

import type { Arguments, Key, SWRConfiguration } from 'swr';
import useSwr from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';
import useSWRMutation from 'swr/mutation';

import type {
  AuthResponse,
  BadRequestResponse,
  CreatePollRequest,
  CreateQuestionRequest,
  Exam,
  GetExams200,
  GetExamsParams,
  GetHomeParams,
  GetPolls200,
  GetPollsParams,
  GetQuestions200,
  GetQuestionsParams,
  GetUserPolls200,
  GetUserPollsParams,
  GetUserQuestions200,
  GetUserQuestionsParams,
  GetUsers200,
  GetUsersParams,
  HomePageData,
  InternalServerErrorResponse,
  NotFoundResponse,
  Poll,
  PostChangePasswordBody,
  PostForgotPasswordBody,
  PostLikeExamBody,
  PostLikePollBody,
  PostLikeQuestionBody,
  PostLoginUserBody,
  PostRegisterUserBody,
  PostResetPasswordBody,
  PostSendVerificationEmailBody,
  PostSubmitAnswer200,
  PostSubmitAnswerBody,
  PostVerifyEmailBody,
  PostVotePollBody,
  Question,
  QuestionSubmission,
  RecentSubmission,
  UnauthorizedResponse,
  UserPrivate,
  UserPublic,
} from './dto';

import { Fetcher } from './fetcher/fetcher';

/**
 * @summary Register a new user
 */
export const postRegisterUser = (postRegisterUserBody: PostRegisterUserBody) => {
  return Fetcher<AuthResponse>({
    url: `/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postRegisterUserBody,
  });
};

export const getPostRegisterUserMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostRegisterUserBody }) => {
    return postRegisterUser(arg);
  };
};
export const getPostRegisterUserMutationKey = () => [`/auth/register`] as const;

export type PostRegisterUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRegisterUser>>
>;
export type PostRegisterUserMutationError = BadRequestResponse | InternalServerErrorResponse;

/**
 * @summary Register a new user
 */
export const usePostRegisterUser = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postRegisterUser>>,
    TError,
    Key,
    PostRegisterUserBody,
    Awaited<ReturnType<typeof postRegisterUser>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostRegisterUserMutationKey();
  const swrFn = getPostRegisterUserMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Login user
 */
export const postLoginUser = (postLoginUserBody: PostLoginUserBody) => {
  return Fetcher<AuthResponse>({
    url: `/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postLoginUserBody,
  });
};

export const getPostLoginUserMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostLoginUserBody }) => {
    return postLoginUser(arg);
  };
};
export const getPostLoginUserMutationKey = () => [`/auth/login`] as const;

export type PostLoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof postLoginUser>>>;
export type PostLoginUserMutationError =
  | BadRequestResponse
  | undefined
  | InternalServerErrorResponse;

/**
 * @summary Login user
 */
export const usePostLoginUser = <
  TError = BadRequestResponse | undefined | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postLoginUser>>,
    TError,
    Key,
    PostLoginUserBody,
    Awaited<ReturnType<typeof postLoginUser>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostLoginUserMutationKey();
  const swrFn = getPostLoginUserMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Request password reset
 */
export const postForgotPassword = (postForgotPasswordBody: PostForgotPasswordBody) => {
  return Fetcher<void>({
    url: `/auth/forgot-password`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postForgotPasswordBody,
  });
};

export const getPostForgotPasswordMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostForgotPasswordBody }) => {
    return postForgotPassword(arg);
  };
};
export const getPostForgotPasswordMutationKey = () => [`/auth/forgot-password`] as const;

export type PostForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postForgotPassword>>
>;
export type PostForgotPasswordMutationError = BadRequestResponse | InternalServerErrorResponse;

/**
 * @summary Request password reset
 */
export const usePostForgotPassword = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postForgotPassword>>,
    TError,
    Key,
    PostForgotPasswordBody,
    Awaited<ReturnType<typeof postForgotPassword>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostForgotPasswordMutationKey();
  const swrFn = getPostForgotPasswordMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Reset password
 */
export const postResetPassword = (postResetPasswordBody: PostResetPasswordBody) => {
  return Fetcher<void>({
    url: `/auth/reset-password`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postResetPasswordBody,
  });
};

export const getPostResetPasswordMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostResetPasswordBody }) => {
    return postResetPassword(arg);
  };
};
export const getPostResetPasswordMutationKey = () => [`/auth/reset-password`] as const;

export type PostResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postResetPassword>>
>;
export type PostResetPasswordMutationError = BadRequestResponse | InternalServerErrorResponse;

/**
 * @summary Reset password
 */
export const usePostResetPassword = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postResetPassword>>,
    TError,
    Key,
    PostResetPasswordBody,
    Awaited<ReturnType<typeof postResetPassword>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostResetPasswordMutationKey();
  const swrFn = getPostResetPasswordMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Change password
 */
export const postChangePassword = (postChangePasswordBody: PostChangePasswordBody) => {
  return Fetcher<void>({
    url: `/auth/change-password`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postChangePasswordBody,
  });
};

export const getPostChangePasswordMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostChangePasswordBody }) => {
    return postChangePassword(arg);
  };
};
export const getPostChangePasswordMutationKey = () => [`/auth/change-password`] as const;

export type PostChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postChangePassword>>
>;
export type PostChangePasswordMutationError = BadRequestResponse | InternalServerErrorResponse;

/**
 * @summary Change password
 */
export const usePostChangePassword = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postChangePassword>>,
    TError,
    Key,
    PostChangePasswordBody,
    Awaited<ReturnType<typeof postChangePassword>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostChangePasswordMutationKey();
  const swrFn = getPostChangePasswordMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Verify email address
 */
export const postVerifyEmail = (postVerifyEmailBody: PostVerifyEmailBody) => {
  return Fetcher<void>({
    url: `/auth/verify-email`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postVerifyEmailBody,
  });
};

export const getPostVerifyEmailMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostVerifyEmailBody }) => {
    return postVerifyEmail(arg);
  };
};
export const getPostVerifyEmailMutationKey = () => [`/auth/verify-email`] as const;

export type PostVerifyEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof postVerifyEmail>>
>;
export type PostVerifyEmailMutationError = BadRequestResponse | InternalServerErrorResponse;

/**
 * @summary Verify email address
 */
export const usePostVerifyEmail = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postVerifyEmail>>,
    TError,
    Key,
    PostVerifyEmailBody,
    Awaited<ReturnType<typeof postVerifyEmail>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostVerifyEmailMutationKey();
  const swrFn = getPostVerifyEmailMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * Sends a email with a verification token link to the user.
 * @summary Send verification email
 */
export const postSendVerificationEmail = (
  postSendVerificationEmailBody: PostSendVerificationEmailBody,
) => {
  return Fetcher<void>({
    url: `/auth/send-verification-email`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postSendVerificationEmailBody,
  });
};

export const getPostSendVerificationEmailMutationFetcher = () => {
  return (_: Key, { arg }: { arg: PostSendVerificationEmailBody }) => {
    return postSendVerificationEmail(arg);
  };
};
export const getPostSendVerificationEmailMutationKey = () =>
  [`/auth/send-verification-email`] as const;

export type PostSendVerificationEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSendVerificationEmail>>
>;
export type PostSendVerificationEmailMutationError =
  | BadRequestResponse
  | InternalServerErrorResponse;

/**
 * @summary Send verification email
 */
export const usePostSendVerificationEmail = <
  TError = BadRequestResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postSendVerificationEmail>>,
    TError,
    Key,
    PostSendVerificationEmailBody,
    Awaited<ReturnType<typeof postSendVerificationEmail>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostSendVerificationEmailMutationKey();
  const swrFn = getPostSendVerificationEmailMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary 获取当前用户信息
 */
export const getCurrentUser = () => {
  return Fetcher<UserPrivate>({ url: `/auth/me`, method: 'GET' });
};

export const getGetCurrentUserKey = () => [`/auth/me`] as const;

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>;
export type GetCurrentUserQueryError =
  | BadRequestResponse
  | UnauthorizedResponse
  | InternalServerErrorResponse;

/**
 * @summary 获取当前用户信息
 */
export const useGetCurrentUser = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getCurrentUser>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
}) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetCurrentUserKey() : null));
  const swrFn = () => getCurrentUser();

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Update current user
 */
export const updateUser = (userPrivate: UserPrivate) => {
  return Fetcher<UserPrivate>({
    url: `/auth/me`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: userPrivate,
  });
};

export const getUpdateUserMutationFetcher = () => {
  return (_: Key, { arg }: { arg: UserPrivate }) => {
    return updateUser(arg);
  };
};
export const getUpdateUserMutationKey = () => [`/auth/me`] as const;

export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>;
export type UpdateUserMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | InternalServerErrorResponse;

/**
 * @summary Update current user
 */
export const useUpdateUser = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    Key,
    UserPrivate,
    Awaited<ReturnType<typeof updateUser>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateUserMutationKey();
  const swrFn = getUpdateUserMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Delete current user
 */
export const deleteUser = () => {
  return Fetcher<void>({ url: `/auth/me`, method: 'DELETE' });
};

export const getDeleteUserMutationFetcher = () => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteUser();
  };
};
export const getDeleteUserMutationKey = () => [`/auth/me`] as const;

export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;
export type DeleteUserMutationError = UnauthorizedResponse | InternalServerErrorResponse;

/**
 * @summary Delete current user
 */
export const useDeleteUser = <
  TError = UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof deleteUser>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteUserMutationKey();
  const swrFn = getDeleteUserMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get homepage data
 */
export const getHome = (params?: GetHomeParams) => {
  return Fetcher<HomePageData>({ url: `/home`, method: 'GET', params });
};

export const getGetHomeKey = (params?: GetHomeParams) =>
  [`/home`, ...(params ? [params] : [])] as const;

export type GetHomeQueryResult = NonNullable<Awaited<ReturnType<typeof getHome>>>;
export type GetHomeQueryError = BadRequestResponse | InternalServerErrorResponse;

/**
 * @summary Get homepage data
 */
export const useGetHome = <TError = BadRequestResponse | InternalServerErrorResponse>(
  params?: GetHomeParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getHome>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetHomeKey(params) : null));
  const swrFn = () => getHome(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get all users
 */
export const getUsers = (params?: GetUsersParams) => {
  return Fetcher<GetUsers200>({ url: `/users`, method: 'GET', params });
};

export const getGetUsersKey = (params?: GetUsersParams) =>
  [`/users`, ...(params ? [params] : [])] as const;

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>;
export type GetUsersQueryError =
  | BadRequestResponse
  | UnauthorizedResponse
  | InternalServerErrorResponse;

/**
 * @summary Get all users
 */
export const useGetUsers = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(
  params?: GetUsersParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUsers>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetUsersKey(params) : null));
  const swrFn = () => getUsers(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get user by ID
 */
export const getUser = (id: string) => {
  return Fetcher<UserPublic>({ url: `/users/${id}`, method: 'GET' });
};

export const getGetUserKey = (id: string) => [`/users/${id}`] as const;

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>;
export type GetUserQueryError = NotFoundResponse | InternalServerErrorResponse;

/**
 * @summary Get user by ID
 */
export const useGetUser = <TError = NotFoundResponse | InternalServerErrorResponse>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUser>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetUserKey(id) : null));
  const swrFn = () => getUser(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get user's created polls
 */
export const getUserPolls = (id: string, params?: GetUserPollsParams) => {
  return Fetcher<GetUserPolls200>({ url: `/users/${id}/polls`, method: 'GET', params });
};

export const getGetUserPollsKey = (id: string, params?: GetUserPollsParams) =>
  [`/users/${id}/polls`, ...(params ? [params] : [])] as const;

export type GetUserPollsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserPolls>>>;
export type GetUserPollsQueryError = NotFoundResponse | InternalServerErrorResponse;

/**
 * @summary Get user's created polls
 */
export const useGetUserPolls = <TError = NotFoundResponse | InternalServerErrorResponse>(
  id: string,
  params?: GetUserPollsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUserPolls>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetUserPollsKey(id, params) : null));
  const swrFn = () => getUserPolls(id, params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get user's created question
 */
export const getUserQuestions = (id: string, params?: GetUserQuestionsParams) => {
  return Fetcher<GetUserQuestions200>({ url: `/users/${id}/questions`, method: 'GET', params });
};

export const getGetUserQuestionsKey = (id: string, params?: GetUserQuestionsParams) =>
  [`/users/${id}/questions`, ...(params ? [params] : [])] as const;

export type GetUserQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserQuestions>>>;
export type GetUserQuestionsQueryError = NotFoundResponse | InternalServerErrorResponse;

/**
 * @summary Get user's created question
 */
export const useGetUserQuestions = <TError = NotFoundResponse | InternalServerErrorResponse>(
  id: string,
  params?: GetUserQuestionsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUserQuestions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetUserQuestionsKey(id, params) : null));
  const swrFn = () => getUserQuestions(id, params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get all questions
 */
export const getQuestions = (params?: GetQuestionsParams) => {
  return Fetcher<GetQuestions200>({ url: `/questions`, method: 'GET', params });
};

export const getGetQuestionsKey = (params?: GetQuestionsParams) =>
  [`/questions`, ...(params ? [params] : [])] as const;

export type GetQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestions>>>;
export type GetQuestionsQueryError = BadRequestResponse | InternalServerErrorResponse;

/**
 * @summary Get all questions
 */
export const useGetQuestions = <TError = BadRequestResponse | InternalServerErrorResponse>(
  params?: GetQuestionsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getQuestions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetQuestionsKey(params) : null));
  const swrFn = () => getQuestions(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Create a new question
 */
export const postCreateQuestion = (createQuestionRequest: CreateQuestionRequest) => {
  return Fetcher<CreateQuestionRequest>({
    url: `/questions`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createQuestionRequest,
  });
};

export const getPostCreateQuestionMutationFetcher = () => {
  return (_: Key, { arg }: { arg: CreateQuestionRequest }) => {
    return postCreateQuestion(arg);
  };
};
export const getPostCreateQuestionMutationKey = () => [`/questions`] as const;

export type PostCreateQuestionMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateQuestion>>
>;
export type PostCreateQuestionMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | InternalServerErrorResponse;

/**
 * @summary Create a new question
 */
export const usePostCreateQuestion = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postCreateQuestion>>,
    TError,
    Key,
    CreateQuestionRequest,
    Awaited<ReturnType<typeof postCreateQuestion>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostCreateQuestionMutationKey();
  const swrFn = getPostCreateQuestionMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get question by ID
 */
export const getQuestion = (id: string) => {
  return Fetcher<Question>({ url: `/questions/${id}`, method: 'GET' });
};

export const getGetQuestionKey = (id: string) => [`/questions/${id}`] as const;

export type GetQuestionQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestion>>>;
export type GetQuestionQueryError =
  | BadRequestResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary Get question by ID
 */
export const useGetQuestion = <
  TError = BadRequestResponse | NotFoundResponse | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getQuestion>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetQuestionKey(id) : null));
  const swrFn = () => getQuestion(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Update question
 */
export const updateQuestion = (id: string, createQuestionRequest: CreateQuestionRequest) => {
  return Fetcher<CreateQuestionRequest>({
    url: `/questions/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: createQuestionRequest,
  });
};

export const getUpdateQuestionMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: CreateQuestionRequest }) => {
    return updateQuestion(id, arg);
  };
};
export const getUpdateQuestionMutationKey = (id: string) => [`/questions/${id}`] as const;

export type UpdateQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof updateQuestion>>>;
export type UpdateQuestionMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary Update question
 */
export const useUpdateQuestion = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateQuestion>>,
      TError,
      Key,
      CreateQuestionRequest,
      Awaited<ReturnType<typeof updateQuestion>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateQuestionMutationKey(id);
  const swrFn = getUpdateQuestionMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Delete question
 */
export const deleteQuestion = (id: string) => {
  return Fetcher<void>({ url: `/questions/${id}`, method: 'DELETE' });
};

export const getDeleteQuestionMutationFetcher = (id: string) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteQuestion(id);
  };
};
export const getDeleteQuestionMutationKey = (id: string) => [`/questions/${id}`] as const;

export type DeleteQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQuestion>>>;
export type DeleteQuestionMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary Delete question
 */
export const useDeleteQuestion = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteQuestion>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteQuestion>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteQuestionMutationKey(id);
  const swrFn = getDeleteQuestionMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * Submit user's answer for a specific question and get result
 * @summary Submit answer for a question
 */
export const postSubmitAnswer = (id: string, postSubmitAnswerBody: PostSubmitAnswerBody) => {
  return Fetcher<PostSubmitAnswer200>({
    url: `/questions/${id}/submit`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postSubmitAnswerBody,
  });
};

export const getPostSubmitAnswerMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostSubmitAnswerBody }) => {
    return postSubmitAnswer(id, arg);
  };
};
export const getPostSubmitAnswerMutationKey = (id: string) => [`/questions/${id}/submit`] as const;

export type PostSubmitAnswerMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSubmitAnswer>>
>;
export type PostSubmitAnswerMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary Submit answer for a question
 */
export const usePostSubmitAnswer = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postSubmitAnswer>>,
      TError,
      Key,
      PostSubmitAnswerBody,
      Awaited<ReturnType<typeof postSubmitAnswer>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostSubmitAnswerMutationKey(id);
  const swrFn = getPostSubmitAnswerMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * Submit user's answer for a specific question and get result
 * @summary Like or dislike a question
 */
export const postLikeQuestion = (id: string, postLikeQuestionBody: PostLikeQuestionBody) => {
  return Fetcher<void>({
    url: `/questions/${id}/like`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postLikeQuestionBody,
  });
};

export const getPostLikeQuestionMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostLikeQuestionBody }) => {
    return postLikeQuestion(id, arg);
  };
};
export const getPostLikeQuestionMutationKey = (id: string) => [`/questions/${id}/like`] as const;

export type PostLikeQuestionMutationResult = NonNullable<
  Awaited<ReturnType<typeof postLikeQuestion>>
>;
export type PostLikeQuestionMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary Like or dislike a question
 */
export const usePostLikeQuestion = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postLikeQuestion>>,
      TError,
      Key,
      PostLikeQuestionBody,
      Awaited<ReturnType<typeof postLikeQuestion>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostLikeQuestionMutationKey(id);
  const swrFn = getPostLikeQuestionMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * Get current user's submission records for a specific question (up to 100 records)
 * @summary Get my submissions for a question
 */
export const getQuestionMySubmissions = (id: string) => {
  return Fetcher<QuestionSubmission[]>({ url: `/questions/${id}/my-answers`, method: 'GET' });
};

export const getGetQuestionMySubmissionsKey = (id: string) =>
  [`/questions/${id}/my-answers`] as const;

export type GetQuestionMySubmissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionMySubmissions>>
>;
export type GetQuestionMySubmissionsQueryError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary Get my submissions for a question
 */
export const useGetQuestionMySubmissions = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getQuestionMySubmissions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetQuestionMySubmissionsKey(id) : null));
  const swrFn = () => getQuestionMySubmissions(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * Get recent submission records from other users for a specific question (up to 100 records)
 * @summary Get recent submissions from other users
 */
export const getQuestionRecentSubmissions = (id: string) => {
  return Fetcher<RecentSubmission[]>({ url: `/questions/${id}/recent`, method: 'GET' });
};

export const getGetQuestionRecentSubmissionsKey = (id: string) =>
  [`/questions/${id}/recent`] as const;

export type GetQuestionRecentSubmissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionRecentSubmissions>>
>;
export type GetQuestionRecentSubmissionsQueryError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary Get recent submissions from other users
 */
export const useGetQuestionRecentSubmissions = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getQuestionRecentSubmissions>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetQuestionRecentSubmissionsKey(id) : null));
  const swrFn = () => getQuestionRecentSubmissions(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get all exams
 */
export const getExams = (params?: GetExamsParams) => {
  return Fetcher<GetExams200>({ url: `/exams`, method: 'GET', params });
};

export const getGetExamsKey = (params?: GetExamsParams) =>
  [`/exams`, ...(params ? [params] : [])] as const;

export type GetExamsQueryResult = NonNullable<Awaited<ReturnType<typeof getExams>>>;
export type GetExamsQueryError = InternalServerErrorResponse;

/**
 * @summary Get all exams
 */
export const useGetExams = <TError = InternalServerErrorResponse>(
  params?: GetExamsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getExams>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetExamsKey(params) : null));
  const swrFn = () => getExams(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Create a new exam
 */
export const postCreateExam = (exam: Exam) => {
  return Fetcher<Exam>({
    url: `/exams`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: exam,
  });
};

export const getPostCreateExamMutationFetcher = () => {
  return (_: Key, { arg }: { arg: Exam }) => {
    return postCreateExam(arg);
  };
};
export const getPostCreateExamMutationKey = () => [`/exams`] as const;

export type PostCreateExamMutationResult = NonNullable<Awaited<ReturnType<typeof postCreateExam>>>;
export type PostCreateExamMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | InternalServerErrorResponse;

/**
 * @summary Create a new exam
 */
export const usePostCreateExam = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postCreateExam>>,
    TError,
    Key,
    Exam,
    Awaited<ReturnType<typeof postCreateExam>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostCreateExamMutationKey();
  const swrFn = getPostCreateExamMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get exam by ID
 */
export const getExam = (id: string) => {
  return Fetcher<Exam>({ url: `/exams/${id}`, method: 'GET' });
};

export const getGetExamKey = (id: string) => [`/exams/${id}`] as const;

export type GetExamQueryResult = NonNullable<Awaited<ReturnType<typeof getExam>>>;
export type GetExamQueryError = BadRequestResponse | NotFoundResponse | InternalServerErrorResponse;

/**
 * @summary Get exam by ID
 */
export const useGetExam = <
  TError = BadRequestResponse | NotFoundResponse | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getExam>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetExamKey(id) : null));
  const swrFn = () => getExam(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Update exam
 */
export const updateExam = (id: string, exam: Exam) => {
  return Fetcher<Exam>({
    url: `/exams/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: exam,
  });
};

export const getUpdateExamMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: Exam }) => {
    return updateExam(id, arg);
  };
};
export const getUpdateExamMutationKey = (id: string) => [`/exams/${id}`] as const;

export type UpdateExamMutationResult = NonNullable<Awaited<ReturnType<typeof updateExam>>>;
export type UpdateExamMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary Update exam
 */
export const useUpdateExam = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateExam>>,
      TError,
      Key,
      Exam,
      Awaited<ReturnType<typeof updateExam>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateExamMutationKey(id);
  const swrFn = getUpdateExamMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Delete exam
 */
export const deleteExam = (id: string) => {
  return Fetcher<void>({ url: `/exams/${id}`, method: 'DELETE' });
};

export const getDeleteExamMutationFetcher = (id: string) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteExam(id);
  };
};
export const getDeleteExamMutationKey = (id: string) => [`/exams/${id}`] as const;

export type DeleteExamMutationResult = NonNullable<Awaited<ReturnType<typeof deleteExam>>>;
export type DeleteExamMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary Delete exam
 */
export const useDeleteExam = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteExam>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteExam>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteExamMutationKey(id);
  const swrFn = getDeleteExamMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary 点赞测验
 */
export const postLikeExam = (id: string, postLikeExamBody: PostLikeExamBody) => {
  return Fetcher<void>({
    url: `/exams/${id}/like`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postLikeExamBody,
  });
};

export const getPostLikeExamMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostLikeExamBody }) => {
    return postLikeExam(id, arg);
  };
};
export const getPostLikeExamMutationKey = (id: string) => [`/exams/${id}/like`] as const;

export type PostLikeExamMutationResult = NonNullable<Awaited<ReturnType<typeof postLikeExam>>>;
export type PostLikeExamMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary 点赞测验
 */
export const usePostLikeExam = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postLikeExam>>,
      TError,
      Key,
      PostLikeExamBody,
      Awaited<ReturnType<typeof postLikeExam>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostLikeExamMutationKey(id);
  const swrFn = getPostLikeExamMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get all polls
 */
export const getPolls = (params?: GetPollsParams) => {
  return Fetcher<GetPolls200>({ url: `/polls`, method: 'GET', params });
};

export const getGetPollsKey = (params?: GetPollsParams) =>
  [`/polls`, ...(params ? [params] : [])] as const;

export type GetPollsQueryResult = NonNullable<Awaited<ReturnType<typeof getPolls>>>;
export type GetPollsQueryError = InternalServerErrorResponse;

/**
 * @summary Get all polls
 */
export const useGetPolls = <TError = InternalServerErrorResponse>(
  params?: GetPollsParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getPolls>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetPollsKey(params) : null));
  const swrFn = () => getPolls(params);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Create new poll
 */
export const postCreatePoll = (createPollRequest: CreatePollRequest) => {
  return Fetcher<Poll>({
    url: `/polls`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createPollRequest,
  });
};

export const getPostCreatePollMutationFetcher = () => {
  return (_: Key, { arg }: { arg: CreatePollRequest }) => {
    return postCreatePoll(arg);
  };
};
export const getPostCreatePollMutationKey = () => [`/polls`] as const;

export type PostCreatePollMutationResult = NonNullable<Awaited<ReturnType<typeof postCreatePoll>>>;
export type PostCreatePollMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | InternalServerErrorResponse;

/**
 * @summary Create new poll
 */
export const usePostCreatePoll = <
  TError = BadRequestResponse | UnauthorizedResponse | InternalServerErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postCreatePoll>>,
    TError,
    Key,
    CreatePollRequest,
    Awaited<ReturnType<typeof postCreatePoll>>
  > & { swrKey?: string };
}) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostCreatePollMutationKey();
  const swrFn = getPostCreatePollMutationFetcher();

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary 获取投票详情（含当前结果）
 */
export const getPoll = (id: string) => {
  return Fetcher<Poll>({ url: `/polls/${id}`, method: 'GET' });
};

export const getGetPollKey = (id: string) => [`/polls/${id}`] as const;

export type GetPollQueryResult = NonNullable<Awaited<ReturnType<typeof getPoll>>>;
export type GetPollQueryError = BadRequestResponse | NotFoundResponse | InternalServerErrorResponse;

/**
 * @summary 获取投票详情（含当前结果）
 */
export const useGetPoll = <
  TError = BadRequestResponse | NotFoundResponse | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getPoll>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetPollKey(id) : null));
  const swrFn = () => getPoll(id);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary 点赞投票
 */
export const postLikePoll = (id: string, postLikePollBody: PostLikePollBody) => {
  return Fetcher<void>({
    url: `/polls/${id}/like`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postLikePollBody,
  });
};

export const getPostLikePollMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostLikePollBody }) => {
    return postLikePoll(id, arg);
  };
};
export const getPostLikePollMutationKey = (id: string) => [`/polls/${id}/like`] as const;

export type PostLikePollMutationResult = NonNullable<Awaited<ReturnType<typeof postLikePoll>>>;
export type PostLikePollMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary 点赞投票
 */
export const usePostLikePoll = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postLikePoll>>,
      TError,
      Key,
      PostLikePollBody,
      Awaited<ReturnType<typeof postLikePoll>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostLikePollMutationKey(id);
  const swrFn = getPostLikePollMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary 投票
 */
export const postVotePoll = (id: string, postVotePollBody: PostVotePollBody) => {
  return Fetcher<void>({
    url: `/polls/${id}/vote`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postVotePollBody,
  });
};

export const getPostVotePollMutationFetcher = (id: string) => {
  return (_: Key, { arg }: { arg: PostVotePollBody }) => {
    return postVotePoll(id, arg);
  };
};
export const getPostVotePollMutationKey = (id: string) => [`/polls/${id}/vote`] as const;

export type PostVotePollMutationResult = NonNullable<Awaited<ReturnType<typeof postVotePoll>>>;
export type PostVotePollMutationError =
  | BadRequestResponse
  | UnauthorizedResponse
  | NotFoundResponse
  | InternalServerErrorResponse;

/**
 * @summary 投票
 */
export const usePostVotePoll = <
  TError =
    | BadRequestResponse
    | UnauthorizedResponse
    | NotFoundResponse
    | InternalServerErrorResponse,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postVotePoll>>,
      TError,
      Key,
      PostVotePollBody,
      Awaited<ReturnType<typeof postVotePoll>>
    > & { swrKey?: string };
  },
) => {
  const { swr: swrOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostVotePollMutationKey(id);
  const swrFn = getPostVotePollMutationFetcher(id);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
